=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

module PlainRouter::OpenAPI
  VERSION = '0.1.1'
end
