=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  # System evidence from a completed Test cites its Test, verdict and selected winner member.
  class ActionReadItemEvidenceAnyOf2 < ApiModelBase
    attr_accessor :test_id

    attr_accessor :verdict_id

    attr_accessor :winner_member_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'test_id' => :'test_id',
        :'verdict_id' => :'verdict_id',
        :'winner_member_id' => :'winner_member_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'test_id' => :'String',
        :'verdict_id' => :'String',
        :'winner_member_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionReadItemEvidenceAnyOf2` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionReadItemEvidenceAnyOf2`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'test_id')
        self.test_id = attributes[:'test_id']
      else
        self.test_id = nil
      end

      if attributes.key?(:'verdict_id')
        self.verdict_id = attributes[:'verdict_id']
      else
        self.verdict_id = nil
      end

      if attributes.key?(:'winner_member_id')
        self.winner_member_id = attributes[:'winner_member_id']
      else
        self.winner_member_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @test_id.nil?
        invalid_properties.push('invalid value for "test_id", test_id cannot be nil.')
      end

      if @verdict_id.nil?
        invalid_properties.push('invalid value for "verdict_id", verdict_id cannot be nil.')
      end

      if @winner_member_id.nil?
        invalid_properties.push('invalid value for "winner_member_id", winner_member_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @test_id.nil?
      return false if @verdict_id.nil?
      return false if @winner_member_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] test_id Value to be assigned
    def test_id=(test_id)
      if test_id.nil?
        fail ArgumentError, 'test_id cannot be nil'
      end

      @test_id = test_id
    end

    # Custom attribute writer method with validation
    # @param [Object] verdict_id Value to be assigned
    def verdict_id=(verdict_id)
      if verdict_id.nil?
        fail ArgumentError, 'verdict_id cannot be nil'
      end

      @verdict_id = verdict_id
    end

    # Custom attribute writer method with validation
    # @param [Object] winner_member_id Value to be assigned
    def winner_member_id=(winner_member_id)
      if winner_member_id.nil?
        fail ArgumentError, 'winner_member_id cannot be nil'
      end

      @winner_member_id = winner_member_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          test_id == o.test_id &&
          verdict_id == o.verdict_id &&
          winner_member_id == o.winner_member_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [test_id, verdict_id, winner_member_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
