=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ActionReadItem < ApiModelBase
    attr_accessor :id

    attr_accessor :batch_id

    attr_accessor :workspace_id

    attr_accessor :type

    attr_accessor :target_entity_type

    attr_accessor :target_entity_id

    attr_accessor :target_entity_name

    attr_accessor :params

    attr_accessor :rationale

    attr_accessor :proposer

    attr_accessor :evidence

    attr_accessor :status

    attr_accessor :batch_status

    attr_accessor :disposition

    attr_accessor :policy_decision

    attr_accessor :policy_reasons

    attr_accessor :policy_result

    attr_accessor :policy_results

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'batch_id' => :'batch_id',
        :'workspace_id' => :'workspace_id',
        :'type' => :'type',
        :'target_entity_type' => :'target_entity_type',
        :'target_entity_id' => :'target_entity_id',
        :'target_entity_name' => :'target_entity_name',
        :'params' => :'params',
        :'rationale' => :'rationale',
        :'proposer' => :'proposer',
        :'evidence' => :'evidence',
        :'status' => :'status',
        :'batch_status' => :'batch_status',
        :'disposition' => :'disposition',
        :'policy_decision' => :'policy_decision',
        :'policy_reasons' => :'policy_reasons',
        :'policy_result' => :'policy_result',
        :'policy_results' => :'policy_results'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'batch_id' => :'String',
        :'workspace_id' => :'Integer',
        :'type' => :'String',
        :'target_entity_type' => :'String',
        :'target_entity_id' => :'String',
        :'target_entity_name' => :'String',
        :'params' => :'ActionProposalReadProposalActionsInnerParams',
        :'rationale' => :'String',
        :'proposer' => :'ActionReadItemProposer',
        :'evidence' => :'ActionReadItemEvidence',
        :'status' => :'String',
        :'batch_status' => :'String',
        :'disposition' => :'ActionCurrentDisposition',
        :'policy_decision' => :'String',
        :'policy_reasons' => :'Array<String>',
        :'policy_result' => :'ActionPolicyResult',
        :'policy_results' => :'Array<ActionPolicyResult>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'target_entity_name',
        :'policy_decision',
        :'policy_result',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionReadItem` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionReadItem`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'batch_id')
        self.batch_id = attributes[:'batch_id']
      else
        self.batch_id = nil
      end

      if attributes.key?(:'workspace_id')
        self.workspace_id = attributes[:'workspace_id']
      else
        self.workspace_id = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'target_entity_type')
        self.target_entity_type = attributes[:'target_entity_type']
      else
        self.target_entity_type = nil
      end

      if attributes.key?(:'target_entity_id')
        self.target_entity_id = attributes[:'target_entity_id']
      else
        self.target_entity_id = nil
      end

      if attributes.key?(:'target_entity_name')
        self.target_entity_name = attributes[:'target_entity_name']
      else
        self.target_entity_name = nil
      end

      if attributes.key?(:'params')
        self.params = attributes[:'params']
      else
        self.params = nil
      end

      if attributes.key?(:'rationale')
        self.rationale = attributes[:'rationale']
      else
        self.rationale = nil
      end

      if attributes.key?(:'proposer')
        self.proposer = attributes[:'proposer']
      end

      if attributes.key?(:'evidence')
        self.evidence = attributes[:'evidence']
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'batch_status')
        self.batch_status = attributes[:'batch_status']
      else
        self.batch_status = nil
      end

      if attributes.key?(:'disposition')
        self.disposition = attributes[:'disposition']
      else
        self.disposition = nil
      end

      if attributes.key?(:'policy_decision')
        self.policy_decision = attributes[:'policy_decision']
      else
        self.policy_decision = nil
      end

      if attributes.key?(:'policy_reasons')
        if (value = attributes[:'policy_reasons']).is_a?(Array)
          self.policy_reasons = value
        end
      else
        self.policy_reasons = nil
      end

      if attributes.key?(:'policy_result')
        self.policy_result = attributes[:'policy_result']
      else
        self.policy_result = nil
      end

      if attributes.key?(:'policy_results')
        if (value = attributes[:'policy_results']).is_a?(Array)
          self.policy_results = value
        end
      else
        self.policy_results = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @batch_id.nil?
        invalid_properties.push('invalid value for "batch_id", batch_id cannot be nil.')
      end

      if @workspace_id.nil?
        invalid_properties.push('invalid value for "workspace_id", workspace_id cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @target_entity_type.nil?
        invalid_properties.push('invalid value for "target_entity_type", target_entity_type cannot be nil.')
      end

      if @target_entity_id.nil?
        invalid_properties.push('invalid value for "target_entity_id", target_entity_id cannot be nil.')
      end

      if @params.nil?
        invalid_properties.push('invalid value for "params", params cannot be nil.')
      end

      if @rationale.nil?
        invalid_properties.push('invalid value for "rationale", rationale cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @batch_status.nil?
        invalid_properties.push('invalid value for "batch_status", batch_status cannot be nil.')
      end

      if @disposition.nil?
        invalid_properties.push('invalid value for "disposition", disposition cannot be nil.')
      end

      if @policy_reasons.nil?
        invalid_properties.push('invalid value for "policy_reasons", policy_reasons cannot be nil.')
      end

      if @policy_results.nil?
        invalid_properties.push('invalid value for "policy_results", policy_results cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @batch_id.nil?
      return false if @workspace_id.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["increase_budget", "decrease_budget", "pause", "resume", "replace_creative", "shift_spend", "rollback", "create_campaign", "create_ad_set", "create_ad", "upload_asset", "adjust_budget", "set_status", "duplicate_ad_with_creative", "duplicate_adset", "duplicate_ad_with_creative_v2"])
      return false unless type_validator.valid?(@type)
      return false if @target_entity_type.nil?
      return false if @target_entity_id.nil?
      return false if @params.nil?
      return false if @rationale.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["pending", "approved_without_execution", "rejected", "executing", "executed_pending_verification", "compensating", "measuring", "verified", "failed", "execution_uncertain", "rolled_back", "blocked"])
      return false unless status_validator.valid?(@status)
      return false if @batch_status.nil?
      batch_status_validator = EnumAttributeValidator.new('String', ["pending", "approved", "approved_without_execution", "auto_approved", "rejected", "executing", "executed_pending_verification", "compensating", "measuring", "completed", "failed", "rolled_back", "rollback_incomplete", "blocked", "halted"])
      return false unless batch_status_validator.valid?(@batch_status)
      return false if @disposition.nil?
      policy_decision_validator = EnumAttributeValidator.new('String', ["allow", "require_approval", "block"])
      return false unless policy_decision_validator.valid?(@policy_decision)
      return false if @policy_reasons.nil?
      return false if @policy_results.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] batch_id Value to be assigned
    def batch_id=(batch_id)
      if batch_id.nil?
        fail ArgumentError, 'batch_id cannot be nil'
      end

      @batch_id = batch_id
    end

    # Custom attribute writer method with validation
    # @param [Object] workspace_id Value to be assigned
    def workspace_id=(workspace_id)
      if workspace_id.nil?
        fail ArgumentError, 'workspace_id cannot be nil'
      end

      @workspace_id = workspace_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["increase_budget", "decrease_budget", "pause", "resume", "replace_creative", "shift_spend", "rollback", "create_campaign", "create_ad_set", "create_ad", "upload_asset", "adjust_budget", "set_status", "duplicate_ad_with_creative", "duplicate_adset", "duplicate_ad_with_creative_v2"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] target_entity_type Value to be assigned
    def target_entity_type=(target_entity_type)
      if target_entity_type.nil?
        fail ArgumentError, 'target_entity_type cannot be nil'
      end

      @target_entity_type = target_entity_type
    end

    # Custom attribute writer method with validation
    # @param [Object] target_entity_id Value to be assigned
    def target_entity_id=(target_entity_id)
      if target_entity_id.nil?
        fail ArgumentError, 'target_entity_id cannot be nil'
      end

      @target_entity_id = target_entity_id
    end

    # Custom attribute writer method with validation
    # @param [Object] params Value to be assigned
    def params=(params)
      if params.nil?
        fail ArgumentError, 'params cannot be nil'
      end

      @params = params
    end

    # Custom attribute writer method with validation
    # @param [Object] rationale Value to be assigned
    def rationale=(rationale)
      if rationale.nil?
        fail ArgumentError, 'rationale cannot be nil'
      end

      @rationale = rationale
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["pending", "approved_without_execution", "rejected", "executing", "executed_pending_verification", "compensating", "measuring", "verified", "failed", "execution_uncertain", "rolled_back", "blocked"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] batch_status Object to be assigned
    def batch_status=(batch_status)
      validator = EnumAttributeValidator.new('String', ["pending", "approved", "approved_without_execution", "auto_approved", "rejected", "executing", "executed_pending_verification", "compensating", "measuring", "completed", "failed", "rolled_back", "rollback_incomplete", "blocked", "halted"])
      unless validator.valid?(batch_status)
        fail ArgumentError, "invalid value for \"batch_status\", must be one of #{validator.allowable_values}."
      end
      @batch_status = batch_status
    end

    # Custom attribute writer method with validation
    # @param [Object] disposition Value to be assigned
    def disposition=(disposition)
      if disposition.nil?
        fail ArgumentError, 'disposition cannot be nil'
      end

      @disposition = disposition
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] policy_decision Object to be assigned
    def policy_decision=(policy_decision)
      validator = EnumAttributeValidator.new('String', ["allow", "require_approval", "block"])
      unless validator.valid?(policy_decision)
        fail ArgumentError, "invalid value for \"policy_decision\", must be one of #{validator.allowable_values}."
      end
      @policy_decision = policy_decision
    end

    # Custom attribute writer method with validation
    # @param [Object] policy_reasons Value to be assigned
    def policy_reasons=(policy_reasons)
      if policy_reasons.nil?
        fail ArgumentError, 'policy_reasons cannot be nil'
      end

      @policy_reasons = policy_reasons
    end

    # Custom attribute writer method with validation
    # @param [Object] policy_results Value to be assigned
    def policy_results=(policy_results)
      if policy_results.nil?
        fail ArgumentError, 'policy_results cannot be nil'
      end

      @policy_results = policy_results
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          batch_id == o.batch_id &&
          workspace_id == o.workspace_id &&
          type == o.type &&
          target_entity_type == o.target_entity_type &&
          target_entity_id == o.target_entity_id &&
          target_entity_name == o.target_entity_name &&
          params == o.params &&
          rationale == o.rationale &&
          proposer == o.proposer &&
          evidence == o.evidence &&
          status == o.status &&
          batch_status == o.batch_status &&
          disposition == o.disposition &&
          policy_decision == o.policy_decision &&
          policy_reasons == o.policy_reasons &&
          policy_result == o.policy_result &&
          policy_results == o.policy_results
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, batch_id, workspace_id, type, target_entity_type, target_entity_id, target_entity_name, params, rationale, proposer, evidence, status, batch_status, disposition, policy_decision, policy_reasons, policy_result, policy_results].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
