=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ActionProposalInputActionsInnerAnyOf10Params < ApiModelBase
    attr_accessor :staged_asset_id

    attr_accessor :asset_type

    attr_accessor :filename

    attr_accessor :content_sha256

    attr_accessor :mime_type

    attr_accessor :size_bytes

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'staged_asset_id' => :'staged_asset_id',
        :'asset_type' => :'asset_type',
        :'filename' => :'filename',
        :'content_sha256' => :'content_sha256',
        :'mime_type' => :'mime_type',
        :'size_bytes' => :'size_bytes'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'staged_asset_id' => :'String',
        :'asset_type' => :'String',
        :'filename' => :'String',
        :'content_sha256' => :'String',
        :'mime_type' => :'String',
        :'size_bytes' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'mime_type',
        :'size_bytes'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionProposalInputActionsInnerAnyOf10Params` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionProposalInputActionsInnerAnyOf10Params`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'staged_asset_id')
        self.staged_asset_id = attributes[:'staged_asset_id']
      else
        self.staged_asset_id = nil
      end

      if attributes.key?(:'asset_type')
        self.asset_type = attributes[:'asset_type']
      else
        self.asset_type = nil
      end

      if attributes.key?(:'filename')
        self.filename = attributes[:'filename']
      else
        self.filename = nil
      end

      if attributes.key?(:'content_sha256')
        self.content_sha256 = attributes[:'content_sha256']
      else
        self.content_sha256 = nil
      end

      if attributes.key?(:'mime_type')
        self.mime_type = attributes[:'mime_type']
      end

      if attributes.key?(:'size_bytes')
        self.size_bytes = attributes[:'size_bytes']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @staged_asset_id.nil?
        invalid_properties.push('invalid value for "staged_asset_id", staged_asset_id cannot be nil.')
      end

      if @staged_asset_id.to_s.length > 255
        invalid_properties.push('invalid value for "staged_asset_id", the character length must be smaller than or equal to 255.')
      end

      pattern = Regexp.new(/^stage_[a-f0-9]{40}$/)
      if @staged_asset_id !~ pattern
        invalid_properties.push("invalid value for \"staged_asset_id\", must conform to the pattern #{pattern}.")
      end

      if @asset_type.nil?
        invalid_properties.push('invalid value for "asset_type", asset_type cannot be nil.')
      end

      if @filename.nil?
        invalid_properties.push('invalid value for "filename", filename cannot be nil.')
      end

      if @filename.to_s.length > 255
        invalid_properties.push('invalid value for "filename", the character length must be smaller than or equal to 255.')
      end

      if @content_sha256.nil?
        invalid_properties.push('invalid value for "content_sha256", content_sha256 cannot be nil.')
      end

      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @content_sha256 !~ pattern
        invalid_properties.push("invalid value for \"content_sha256\", must conform to the pattern #{pattern}.")
      end

      if !@mime_type.nil? && @mime_type.to_s.length > 255
        invalid_properties.push('invalid value for "mime_type", the character length must be smaller than or equal to 255.')
      end

      if !@size_bytes.nil? && @size_bytes < 1
        invalid_properties.push('invalid value for "size_bytes", must be greater than or equal to 1.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @staged_asset_id.nil?
      return false if @staged_asset_id.to_s.length > 255
      return false if @staged_asset_id !~ Regexp.new(/^stage_[a-f0-9]{40}$/)
      return false if @asset_type.nil?
      asset_type_validator = EnumAttributeValidator.new('String', ["image"])
      return false unless asset_type_validator.valid?(@asset_type)
      return false if @filename.nil?
      return false if @filename.to_s.length > 255
      return false if @content_sha256.nil?
      return false if @content_sha256 !~ Regexp.new(/^[a-f0-9]{64}$/)
      return false if !@mime_type.nil? && @mime_type.to_s.length > 255
      return false if !@size_bytes.nil? && @size_bytes < 1
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] staged_asset_id Value to be assigned
    def staged_asset_id=(staged_asset_id)
      if staged_asset_id.nil?
        fail ArgumentError, 'staged_asset_id cannot be nil'
      end

      if staged_asset_id.to_s.length > 255
        fail ArgumentError, 'invalid value for "staged_asset_id", the character length must be smaller than or equal to 255.'
      end

      pattern = Regexp.new(/^stage_[a-f0-9]{40}$/)
      if staged_asset_id !~ pattern
        fail ArgumentError, "invalid value for \"staged_asset_id\", must conform to the pattern #{pattern}."
      end

      @staged_asset_id = staged_asset_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] asset_type Object to be assigned
    def asset_type=(asset_type)
      validator = EnumAttributeValidator.new('String', ["image"])
      unless validator.valid?(asset_type)
        fail ArgumentError, "invalid value for \"asset_type\", must be one of #{validator.allowable_values}."
      end
      @asset_type = asset_type
    end

    # Custom attribute writer method with validation
    # @param [Object] filename Value to be assigned
    def filename=(filename)
      if filename.nil?
        fail ArgumentError, 'filename cannot be nil'
      end

      if filename.to_s.length > 255
        fail ArgumentError, 'invalid value for "filename", the character length must be smaller than or equal to 255.'
      end

      @filename = filename
    end

    # Custom attribute writer method with validation
    # @param [Object] content_sha256 Value to be assigned
    def content_sha256=(content_sha256)
      if content_sha256.nil?
        fail ArgumentError, 'content_sha256 cannot be nil'
      end

      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if content_sha256 !~ pattern
        fail ArgumentError, "invalid value for \"content_sha256\", must conform to the pattern #{pattern}."
      end

      @content_sha256 = content_sha256
    end

    # Custom attribute writer method with validation
    # @param [Object] mime_type Value to be assigned
    def mime_type=(mime_type)
      if !mime_type.nil? && mime_type.to_s.length > 255
        fail ArgumentError, 'invalid value for "mime_type", the character length must be smaller than or equal to 255.'
      end

      @mime_type = mime_type
    end

    # Custom attribute writer method with validation
    # @param [Object] size_bytes Value to be assigned
    def size_bytes=(size_bytes)
      if !size_bytes.nil? && size_bytes < 1
        fail ArgumentError, 'invalid value for "size_bytes", must be greater than or equal to 1.'
      end

      @size_bytes = size_bytes
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          staged_asset_id == o.staged_asset_id &&
          asset_type == o.asset_type &&
          filename == o.filename &&
          content_sha256 == o.content_sha256 &&
          mime_type == o.mime_type &&
          size_bytes == o.size_bytes
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [staged_asset_id, asset_type, filename, content_sha256, mime_type, size_bytes].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
