=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ActionReadItemEvidenceAnyOf1 < ApiModelBase
    attr_accessor :rule_id

    attr_accessor :revision_id

    attr_accessor :run_id

    attr_accessor :decision_id

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'rule_id' => :'rule_id',
        :'revision_id' => :'revision_id',
        :'run_id' => :'run_id',
        :'decision_id' => :'decision_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'rule_id' => :'String',
        :'revision_id' => :'String',
        :'run_id' => :'String',
        :'decision_id' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionReadItemEvidenceAnyOf1` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionReadItemEvidenceAnyOf1`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'rule_id')
        self.rule_id = attributes[:'rule_id']
      else
        self.rule_id = nil
      end

      if attributes.key?(:'revision_id')
        self.revision_id = attributes[:'revision_id']
      else
        self.revision_id = nil
      end

      if attributes.key?(:'run_id')
        self.run_id = attributes[:'run_id']
      else
        self.run_id = nil
      end

      if attributes.key?(:'decision_id')
        self.decision_id = attributes[:'decision_id']
      else
        self.decision_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @rule_id.nil?
        invalid_properties.push('invalid value for "rule_id", rule_id cannot be nil.')
      end

      if @revision_id.nil?
        invalid_properties.push('invalid value for "revision_id", revision_id cannot be nil.')
      end

      if @run_id.nil?
        invalid_properties.push('invalid value for "run_id", run_id cannot be nil.')
      end

      if @decision_id.nil?
        invalid_properties.push('invalid value for "decision_id", decision_id cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @rule_id.nil?
      return false if @revision_id.nil?
      return false if @run_id.nil?
      return false if @decision_id.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] rule_id Value to be assigned
    def rule_id=(rule_id)
      if rule_id.nil?
        fail ArgumentError, 'rule_id cannot be nil'
      end

      @rule_id = rule_id
    end

    # Custom attribute writer method with validation
    # @param [Object] revision_id Value to be assigned
    def revision_id=(revision_id)
      if revision_id.nil?
        fail ArgumentError, 'revision_id cannot be nil'
      end

      @revision_id = revision_id
    end

    # Custom attribute writer method with validation
    # @param [Object] run_id Value to be assigned
    def run_id=(run_id)
      if run_id.nil?
        fail ArgumentError, 'run_id cannot be nil'
      end

      @run_id = run_id
    end

    # Custom attribute writer method with validation
    # @param [Object] decision_id Value to be assigned
    def decision_id=(decision_id)
      if decision_id.nil?
        fail ArgumentError, 'decision_id cannot be nil'
      end

      @decision_id = decision_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          rule_id == o.rule_id &&
          revision_id == o.revision_id &&
          run_id == o.run_id &&
          decision_id == o.decision_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [rule_id, revision_id, run_id, decision_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
