=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ActionCurrentDispositionOutcomePayloadBaselineAnyOf < ApiModelBase
    attr_accessor :scope

    # Three whole days in the ad account timezone; excludes the change day.
    attr_accessor :days

    attr_accessor :currency

    attr_accessor :timezone

    # Decimal spend in ISO currency minor units; null when daily mirror data is missing.
    attr_accessor :spend_minor

    # Arrivals counted by PlainRouter through Signals, never provider conversions.
    attr_accessor :counted_arrivals

    # Spend divided by counted arrivals, in ISO currency minor units, displayed to six decimal places.
    attr_accessor :cost_per_counted_arrival_minor

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'scope' => :'scope',
        :'days' => :'days',
        :'currency' => :'currency',
        :'timezone' => :'timezone',
        :'spend_minor' => :'spend_minor',
        :'counted_arrivals' => :'counted_arrivals',
        :'cost_per_counted_arrival_minor' => :'cost_per_counted_arrival_minor'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'scope' => :'String',
        :'days' => :'Array<Date>',
        :'currency' => :'String',
        :'timezone' => :'String',
        :'spend_minor' => :'String',
        :'counted_arrivals' => :'Integer',
        :'cost_per_counted_arrival_minor' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'currency',
        :'spend_minor',
        :'counted_arrivals',
        :'cost_per_counted_arrival_minor'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionCurrentDispositionOutcomePayloadBaselineAnyOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionCurrentDispositionOutcomePayloadBaselineAnyOf`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'scope')
        self.scope = attributes[:'scope']
      end

      if attributes.key?(:'days')
        if (value = attributes[:'days']).is_a?(Array)
          self.days = value
        end
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      end

      if attributes.key?(:'spend_minor')
        self.spend_minor = attributes[:'spend_minor']
      end

      if attributes.key?(:'counted_arrivals')
        self.counted_arrivals = attributes[:'counted_arrivals']
      end

      if attributes.key?(:'cost_per_counted_arrival_minor')
        self.cost_per_counted_arrival_minor = attributes[:'cost_per_counted_arrival_minor']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      scope_validator = EnumAttributeValidator.new('String', ["target", "rest_of_account"])
      return false unless scope_validator.valid?(@scope)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] scope Object to be assigned
    def scope=(scope)
      validator = EnumAttributeValidator.new('String', ["target", "rest_of_account"])
      unless validator.valid?(scope)
        fail ArgumentError, "invalid value for \"scope\", must be one of #{validator.allowable_values}."
      end
      @scope = scope
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          scope == o.scope &&
          days == o.days &&
          currency == o.currency &&
          timezone == o.timezone &&
          spend_minor == o.spend_minor &&
          counted_arrivals == o.counted_arrivals &&
          cost_per_counted_arrival_minor == o.cost_per_counted_arrival_minor
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [scope, days, currency, timezone, spend_minor, counted_arrivals, cost_per_counted_arrival_minor].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
