=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ActionDecisionReceiptRead < ApiModelBase
    attr_accessor :document

    attr_accessor :document_sha256

    attr_accessor :chain_entry

    attr_accessor :disposition

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'document' => :'document',
        :'document_sha256' => :'document_sha256',
        :'chain_entry' => :'chain_entry',
        :'disposition' => :'disposition'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'document' => :'Hash<String, Object>',
        :'document_sha256' => :'String',
        :'chain_entry' => :'ActionDecisionReceiptReadChainEntry',
        :'disposition' => :'ActionCurrentDisposition'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionDecisionReceiptRead` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionDecisionReceiptRead`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'document')
        if (value = attributes[:'document']).is_a?(Hash)
          self.document = value
        end
      else
        self.document = nil
      end

      if attributes.key?(:'document_sha256')
        self.document_sha256 = attributes[:'document_sha256']
      else
        self.document_sha256 = nil
      end

      if attributes.key?(:'chain_entry')
        self.chain_entry = attributes[:'chain_entry']
      else
        self.chain_entry = nil
      end

      if attributes.key?(:'disposition')
        self.disposition = attributes[:'disposition']
      else
        self.disposition = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @document.nil?
        invalid_properties.push('invalid value for "document", document cannot be nil.')
      end

      if @document_sha256.nil?
        invalid_properties.push('invalid value for "document_sha256", document_sha256 cannot be nil.')
      end

      if @chain_entry.nil?
        invalid_properties.push('invalid value for "chain_entry", chain_entry cannot be nil.')
      end

      if @disposition.nil?
        invalid_properties.push('invalid value for "disposition", disposition cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @document.nil?
      return false if @document_sha256.nil?
      return false if @chain_entry.nil?
      return false if @disposition.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] document Value to be assigned
    def document=(document)
      if document.nil?
        fail ArgumentError, 'document cannot be nil'
      end

      @document = document
    end

    # Custom attribute writer method with validation
    # @param [Object] document_sha256 Value to be assigned
    def document_sha256=(document_sha256)
      if document_sha256.nil?
        fail ArgumentError, 'document_sha256 cannot be nil'
      end

      @document_sha256 = document_sha256
    end

    # Custom attribute writer method with validation
    # @param [Object] chain_entry Value to be assigned
    def chain_entry=(chain_entry)
      if chain_entry.nil?
        fail ArgumentError, 'chain_entry cannot be nil'
      end

      @chain_entry = chain_entry
    end

    # Custom attribute writer method with validation
    # @param [Object] disposition Value to be assigned
    def disposition=(disposition)
      if disposition.nil?
        fail ArgumentError, 'disposition cannot be nil'
      end

      @disposition = disposition
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          document == o.document &&
          document_sha256 == o.document_sha256 &&
          chain_entry == o.chain_entry &&
          disposition == o.disposition
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [document, document_sha256, chain_entry, disposition].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
