=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ActionDryRunReadDryRunActionsInnerAnyOf < ApiModelBase
    attr_accessor :type

    attr_accessor :target_entity

    attr_accessor :status

    attr_accessor :policy_decision

    attr_accessor :policy_reasons

    attr_accessor :approval_required

    attr_accessor :would_auto_execute

    attr_accessor :diff

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'type' => :'type',
        :'target_entity' => :'target_entity',
        :'status' => :'status',
        :'policy_decision' => :'policy_decision',
        :'policy_reasons' => :'policy_reasons',
        :'approval_required' => :'approval_required',
        :'would_auto_execute' => :'would_auto_execute',
        :'diff' => :'diff'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'type' => :'String',
        :'target_entity' => :'ActionDryRunReadDryRunActionsInnerAnyOfTargetEntity',
        :'status' => :'String',
        :'policy_decision' => :'String',
        :'policy_reasons' => :'Array<String>',
        :'approval_required' => :'Boolean',
        :'would_auto_execute' => :'Boolean',
        :'diff' => :'ActionDryRunReadDryRunActionsInnerAnyOfDiff'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ActionDryRunReadDryRunActionsInnerAnyOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ActionDryRunReadDryRunActionsInnerAnyOf`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'target_entity')
        self.target_entity = attributes[:'target_entity']
      else
        self.target_entity = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'policy_decision')
        self.policy_decision = attributes[:'policy_decision']
      else
        self.policy_decision = nil
      end

      if attributes.key?(:'policy_reasons')
        if (value = attributes[:'policy_reasons']).is_a?(Array)
          self.policy_reasons = value
        end
      else
        self.policy_reasons = nil
      end

      if attributes.key?(:'approval_required')
        self.approval_required = attributes[:'approval_required']
      else
        self.approval_required = nil
      end

      if attributes.key?(:'would_auto_execute')
        self.would_auto_execute = attributes[:'would_auto_execute']
      else
        self.would_auto_execute = nil
      end

      if attributes.key?(:'diff')
        self.diff = attributes[:'diff']
      else
        self.diff = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @target_entity.nil?
        invalid_properties.push('invalid value for "target_entity", target_entity cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @policy_decision.nil?
        invalid_properties.push('invalid value for "policy_decision", policy_decision cannot be nil.')
      end

      if @policy_reasons.nil?
        invalid_properties.push('invalid value for "policy_reasons", policy_reasons cannot be nil.')
      end

      if @approval_required.nil?
        invalid_properties.push('invalid value for "approval_required", approval_required cannot be nil.')
      end

      if @would_auto_execute.nil?
        invalid_properties.push('invalid value for "would_auto_execute", would_auto_execute cannot be nil.')
      end

      if @diff.nil?
        invalid_properties.push('invalid value for "diff", diff cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["increase_budget", "decrease_budget", "pause", "resume", "replace_creative", "shift_spend", "rollback", "create_campaign", "create_ad_set", "create_ad", "upload_asset", "adjust_budget", "set_status", "duplicate_ad_with_creative", "duplicate_adset", "duplicate_ad_with_creative_v2"])
      return false unless type_validator.valid?(@type)
      return false if @target_entity.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["evaluated"])
      return false unless status_validator.valid?(@status)
      return false if @policy_decision.nil?
      policy_decision_validator = EnumAttributeValidator.new('String', ["allow", "require_approval", "block"])
      return false unless policy_decision_validator.valid?(@policy_decision)
      return false if @policy_reasons.nil?
      return false if @approval_required.nil?
      return false if @would_auto_execute.nil?
      return false if @diff.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["increase_budget", "decrease_budget", "pause", "resume", "replace_creative", "shift_spend", "rollback", "create_campaign", "create_ad_set", "create_ad", "upload_asset", "adjust_budget", "set_status", "duplicate_ad_with_creative", "duplicate_adset", "duplicate_ad_with_creative_v2"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] target_entity Value to be assigned
    def target_entity=(target_entity)
      if target_entity.nil?
        fail ArgumentError, 'target_entity cannot be nil'
      end

      @target_entity = target_entity
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["evaluated"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] policy_decision Object to be assigned
    def policy_decision=(policy_decision)
      validator = EnumAttributeValidator.new('String', ["allow", "require_approval", "block"])
      unless validator.valid?(policy_decision)
        fail ArgumentError, "invalid value for \"policy_decision\", must be one of #{validator.allowable_values}."
      end
      @policy_decision = policy_decision
    end

    # Custom attribute writer method with validation
    # @param [Object] policy_reasons Value to be assigned
    def policy_reasons=(policy_reasons)
      if policy_reasons.nil?
        fail ArgumentError, 'policy_reasons cannot be nil'
      end

      @policy_reasons = policy_reasons
    end

    # Custom attribute writer method with validation
    # @param [Object] approval_required Value to be assigned
    def approval_required=(approval_required)
      if approval_required.nil?
        fail ArgumentError, 'approval_required cannot be nil'
      end

      @approval_required = approval_required
    end

    # Custom attribute writer method with validation
    # @param [Object] would_auto_execute Value to be assigned
    def would_auto_execute=(would_auto_execute)
      if would_auto_execute.nil?
        fail ArgumentError, 'would_auto_execute cannot be nil'
      end

      @would_auto_execute = would_auto_execute
    end

    # Custom attribute writer method with validation
    # @param [Object] diff Value to be assigned
    def diff=(diff)
      if diff.nil?
        fail ArgumentError, 'diff cannot be nil'
      end

      @diff = diff
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          type == o.type &&
          target_entity == o.target_entity &&
          status == o.status &&
          policy_decision == o.policy_decision &&
          policy_reasons == o.policy_reasons &&
          approval_required == o.approval_required &&
          would_auto_execute == o.would_auto_execute &&
          diff == o.diff
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [type, target_entity, status, policy_decision, policy_reasons, approval_required, would_auto_execute, diff].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
