=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class AdTestCreateReadTestVerdictHaltDetails < ApiModelBase
    attr_accessor :ad_id

    attr_accessor :effective_status

    attr_accessor :date

    attr_accessor :link_clicks

    attr_accessor :counted_arrivals

    attr_accessor :ad_test_member_id

    attr_accessor :baseline

    attr_accessor :observed_destinations

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'ad_id' => :'ad_id',
        :'effective_status' => :'effective_status',
        :'date' => :'date',
        :'link_clicks' => :'link_clicks',
        :'counted_arrivals' => :'counted_arrivals',
        :'ad_test_member_id' => :'ad_test_member_id',
        :'baseline' => :'baseline',
        :'observed_destinations' => :'observed_destinations'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'ad_id' => :'String',
        :'effective_status' => :'String',
        :'date' => :'Date',
        :'link_clicks' => :'Integer',
        :'counted_arrivals' => :'Integer',
        :'ad_test_member_id' => :'String',
        :'baseline' => :'AdTestCreateReadTestVerdictHaltDetailsBaseline',
        :'observed_destinations' => :'Array<AdTestCreateReadTestVerdictHaltDetailsObservedDestinationsInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::AdTestCreateReadTestVerdictHaltDetails` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::AdTestCreateReadTestVerdictHaltDetails`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'ad_id')
        self.ad_id = attributes[:'ad_id']
      end

      if attributes.key?(:'effective_status')
        self.effective_status = attributes[:'effective_status']
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      end

      if attributes.key?(:'link_clicks')
        self.link_clicks = attributes[:'link_clicks']
      end

      if attributes.key?(:'counted_arrivals')
        self.counted_arrivals = attributes[:'counted_arrivals']
      end

      if attributes.key?(:'ad_test_member_id')
        self.ad_test_member_id = attributes[:'ad_test_member_id']
      end

      if attributes.key?(:'baseline')
        self.baseline = attributes[:'baseline']
      end

      if attributes.key?(:'observed_destinations')
        if (value = attributes[:'observed_destinations']).is_a?(Array)
          self.observed_destinations = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@ad_test_member_id.nil? && @ad_test_member_id.to_s.length > 26
        invalid_properties.push('invalid value for "ad_test_member_id", the character length must be smaller than or equal to 26.')
      end

      if !@ad_test_member_id.nil? && @ad_test_member_id.to_s.length < 26
        invalid_properties.push('invalid value for "ad_test_member_id", the character length must be greater than or equal to 26.')
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if !@ad_test_member_id.nil? && @ad_test_member_id !~ pattern
        invalid_properties.push("invalid value for \"ad_test_member_id\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      effective_status_validator = EnumAttributeValidator.new('String', ["DISAPPROVED", "WITH_ISSUES"])
      return false unless effective_status_validator.valid?(@effective_status)
      return false if !@ad_test_member_id.nil? && @ad_test_member_id.to_s.length > 26
      return false if !@ad_test_member_id.nil? && @ad_test_member_id.to_s.length < 26
      return false if !@ad_test_member_id.nil? && @ad_test_member_id !~ Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] effective_status Object to be assigned
    def effective_status=(effective_status)
      validator = EnumAttributeValidator.new('String', ["DISAPPROVED", "WITH_ISSUES"])
      unless validator.valid?(effective_status)
        fail ArgumentError, "invalid value for \"effective_status\", must be one of #{validator.allowable_values}."
      end
      @effective_status = effective_status
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_test_member_id Value to be assigned
    def ad_test_member_id=(ad_test_member_id)
      if ad_test_member_id.nil?
        fail ArgumentError, 'ad_test_member_id cannot be nil'
      end

      if ad_test_member_id.to_s.length > 26
        fail ArgumentError, 'invalid value for "ad_test_member_id", the character length must be smaller than or equal to 26.'
      end

      if ad_test_member_id.to_s.length < 26
        fail ArgumentError, 'invalid value for "ad_test_member_id", the character length must be greater than or equal to 26.'
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if ad_test_member_id !~ pattern
        fail ArgumentError, "invalid value for \"ad_test_member_id\", must conform to the pattern #{pattern}."
      end

      @ad_test_member_id = ad_test_member_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          ad_id == o.ad_id &&
          effective_status == o.effective_status &&
          date == o.date &&
          link_clicks == o.link_clicks &&
          counted_arrivals == o.counted_arrivals &&
          ad_test_member_id == o.ad_test_member_id &&
          baseline == o.baseline &&
          observed_destinations == o.observed_destinations
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [ad_id, effective_status, date, link_clicks, counted_arrivals, ad_test_member_id, baseline, observed_destinations].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
