=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class AdTest < ApiModelBase
    attr_accessor :id

    attr_accessor :workspace_id

    attr_accessor :platform_ad_account_id

    attr_accessor :ad_set_id

    attr_accessor :axis

    attr_accessor :event_name

    attr_accessor :arrivals_floor

    attr_accessor :minimum_conversions

    attr_accessor :maximum_days

    attr_accessor :maximum_spend_minor

    attr_accessor :anomaly_threshold_percent

    attr_accessor :currency

    attr_accessor :timezone

    attr_accessor :first_day

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :count_health_click_threshold

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'workspace_id' => :'workspace_id',
        :'platform_ad_account_id' => :'platform_ad_account_id',
        :'ad_set_id' => :'ad_set_id',
        :'axis' => :'axis',
        :'event_name' => :'event_name',
        :'arrivals_floor' => :'arrivals_floor',
        :'minimum_conversions' => :'minimum_conversions',
        :'maximum_days' => :'maximum_days',
        :'maximum_spend_minor' => :'maximum_spend_minor',
        :'anomaly_threshold_percent' => :'anomaly_threshold_percent',
        :'currency' => :'currency',
        :'timezone' => :'timezone',
        :'first_day' => :'first_day',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'count_health_click_threshold' => :'count_health_click_threshold'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'workspace_id' => :'Integer',
        :'platform_ad_account_id' => :'Integer',
        :'ad_set_id' => :'String',
        :'axis' => :'String',
        :'event_name' => :'String',
        :'arrivals_floor' => :'Integer',
        :'minimum_conversions' => :'Integer',
        :'maximum_days' => :'Integer',
        :'maximum_spend_minor' => :'String',
        :'anomaly_threshold_percent' => :'String',
        :'currency' => :'String',
        :'timezone' => :'String',
        :'first_day' => :'Time',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'count_health_click_threshold' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'maximum_spend_minor',
        :'count_health_click_threshold'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::AdTest` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::AdTest`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'workspace_id')
        self.workspace_id = attributes[:'workspace_id']
      else
        self.workspace_id = nil
      end

      if attributes.key?(:'platform_ad_account_id')
        self.platform_ad_account_id = attributes[:'platform_ad_account_id']
      else
        self.platform_ad_account_id = nil
      end

      if attributes.key?(:'ad_set_id')
        self.ad_set_id = attributes[:'ad_set_id']
      else
        self.ad_set_id = nil
      end

      if attributes.key?(:'axis')
        self.axis = attributes[:'axis']
      else
        self.axis = nil
      end

      if attributes.key?(:'event_name')
        self.event_name = attributes[:'event_name']
      else
        self.event_name = nil
      end

      if attributes.key?(:'arrivals_floor')
        self.arrivals_floor = attributes[:'arrivals_floor']
      else
        self.arrivals_floor = nil
      end

      if attributes.key?(:'minimum_conversions')
        self.minimum_conversions = attributes[:'minimum_conversions']
      else
        self.minimum_conversions = nil
      end

      if attributes.key?(:'maximum_days')
        self.maximum_days = attributes[:'maximum_days']
      else
        self.maximum_days = nil
      end

      if attributes.key?(:'maximum_spend_minor')
        self.maximum_spend_minor = attributes[:'maximum_spend_minor']
      else
        self.maximum_spend_minor = nil
      end

      if attributes.key?(:'anomaly_threshold_percent')
        self.anomaly_threshold_percent = attributes[:'anomaly_threshold_percent']
      else
        self.anomaly_threshold_percent = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'timezone')
        self.timezone = attributes[:'timezone']
      else
        self.timezone = nil
      end

      if attributes.key?(:'first_day')
        self.first_day = attributes[:'first_day']
      else
        self.first_day = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'count_health_click_threshold')
        self.count_health_click_threshold = attributes[:'count_health_click_threshold']
      else
        self.count_health_click_threshold = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @workspace_id.nil?
        invalid_properties.push('invalid value for "workspace_id", workspace_id cannot be nil.')
      end

      if @platform_ad_account_id.nil?
        invalid_properties.push('invalid value for "platform_ad_account_id", platform_ad_account_id cannot be nil.')
      end

      if @ad_set_id.nil?
        invalid_properties.push('invalid value for "ad_set_id", ad_set_id cannot be nil.')
      end

      if @axis.nil?
        invalid_properties.push('invalid value for "axis", axis cannot be nil.')
      end

      if @event_name.nil?
        invalid_properties.push('invalid value for "event_name", event_name cannot be nil.')
      end

      if @arrivals_floor.nil?
        invalid_properties.push('invalid value for "arrivals_floor", arrivals_floor cannot be nil.')
      end

      if @minimum_conversions.nil?
        invalid_properties.push('invalid value for "minimum_conversions", minimum_conversions cannot be nil.')
      end

      if @maximum_days.nil?
        invalid_properties.push('invalid value for "maximum_days", maximum_days cannot be nil.')
      end

      if @anomaly_threshold_percent.nil?
        invalid_properties.push('invalid value for "anomaly_threshold_percent", anomaly_threshold_percent cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @timezone.nil?
        invalid_properties.push('invalid value for "timezone", timezone cannot be nil.')
      end

      if @first_day.nil?
        invalid_properties.push('invalid value for "first_day", first_day cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @updated_at.nil?
        invalid_properties.push('invalid value for "updated_at", updated_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @workspace_id.nil?
      return false if @platform_ad_account_id.nil?
      return false if @ad_set_id.nil?
      return false if @axis.nil?
      return false if @event_name.nil?
      return false if @arrivals_floor.nil?
      return false if @minimum_conversions.nil?
      return false if @maximum_days.nil?
      return false if @anomaly_threshold_percent.nil?
      return false if @currency.nil?
      return false if @timezone.nil?
      return false if @first_day.nil?
      return false if @created_at.nil?
      return false if @updated_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] workspace_id Value to be assigned
    def workspace_id=(workspace_id)
      if workspace_id.nil?
        fail ArgumentError, 'workspace_id cannot be nil'
      end

      @workspace_id = workspace_id
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_ad_account_id Value to be assigned
    def platform_ad_account_id=(platform_ad_account_id)
      if platform_ad_account_id.nil?
        fail ArgumentError, 'platform_ad_account_id cannot be nil'
      end

      @platform_ad_account_id = platform_ad_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_set_id Value to be assigned
    def ad_set_id=(ad_set_id)
      if ad_set_id.nil?
        fail ArgumentError, 'ad_set_id cannot be nil'
      end

      @ad_set_id = ad_set_id
    end

    # Custom attribute writer method with validation
    # @param [Object] axis Value to be assigned
    def axis=(axis)
      if axis.nil?
        fail ArgumentError, 'axis cannot be nil'
      end

      @axis = axis
    end

    # Custom attribute writer method with validation
    # @param [Object] event_name Value to be assigned
    def event_name=(event_name)
      if event_name.nil?
        fail ArgumentError, 'event_name cannot be nil'
      end

      @event_name = event_name
    end

    # Custom attribute writer method with validation
    # @param [Object] arrivals_floor Value to be assigned
    def arrivals_floor=(arrivals_floor)
      if arrivals_floor.nil?
        fail ArgumentError, 'arrivals_floor cannot be nil'
      end

      @arrivals_floor = arrivals_floor
    end

    # Custom attribute writer method with validation
    # @param [Object] minimum_conversions Value to be assigned
    def minimum_conversions=(minimum_conversions)
      if minimum_conversions.nil?
        fail ArgumentError, 'minimum_conversions cannot be nil'
      end

      @minimum_conversions = minimum_conversions
    end

    # Custom attribute writer method with validation
    # @param [Object] maximum_days Value to be assigned
    def maximum_days=(maximum_days)
      if maximum_days.nil?
        fail ArgumentError, 'maximum_days cannot be nil'
      end

      @maximum_days = maximum_days
    end

    # Custom attribute writer method with validation
    # @param [Object] anomaly_threshold_percent Value to be assigned
    def anomaly_threshold_percent=(anomaly_threshold_percent)
      if anomaly_threshold_percent.nil?
        fail ArgumentError, 'anomaly_threshold_percent cannot be nil'
      end

      @anomaly_threshold_percent = anomaly_threshold_percent
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] timezone Value to be assigned
    def timezone=(timezone)
      if timezone.nil?
        fail ArgumentError, 'timezone cannot be nil'
      end

      @timezone = timezone
    end

    # Custom attribute writer method with validation
    # @param [Object] first_day Value to be assigned
    def first_day=(first_day)
      if first_day.nil?
        fail ArgumentError, 'first_day cannot be nil'
      end

      @first_day = first_day
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] updated_at Value to be assigned
    def updated_at=(updated_at)
      if updated_at.nil?
        fail ArgumentError, 'updated_at cannot be nil'
      end

      @updated_at = updated_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          workspace_id == o.workspace_id &&
          platform_ad_account_id == o.platform_ad_account_id &&
          ad_set_id == o.ad_set_id &&
          axis == o.axis &&
          event_name == o.event_name &&
          arrivals_floor == o.arrivals_floor &&
          minimum_conversions == o.minimum_conversions &&
          maximum_days == o.maximum_days &&
          maximum_spend_minor == o.maximum_spend_minor &&
          anomaly_threshold_percent == o.anomaly_threshold_percent &&
          currency == o.currency &&
          timezone == o.timezone &&
          first_day == o.first_day &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          count_health_click_threshold == o.count_health_click_threshold
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, workspace_id, platform_ad_account_id, ad_set_id, axis, event_name, arrivals_floor, minimum_conversions, maximum_days, maximum_spend_minor, anomaly_threshold_percent, currency, timezone, first_day, created_at, updated_at, count_health_click_threshold].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
