=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class AdTestCreateReadTestVerdictDailyFactsInner < ApiModelBase
    attr_accessor :date

    attr_accessor :ad_test_member_id

    attr_accessor :ad_id

    # Exact spend in Meta minor units for the account currency, including any stored fractional component.
    attr_accessor :spend_minor

    # Account-currency spend in major units.
    attr_accessor :spend

    attr_accessor :impressions

    attr_accessor :inline_link_clicks

    attr_accessor :counted_arrivals

    attr_accessor :recorded_conversions

    attr_accessor :admitted_conversions

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'date' => :'date',
        :'ad_test_member_id' => :'ad_test_member_id',
        :'ad_id' => :'ad_id',
        :'spend_minor' => :'spend_minor',
        :'spend' => :'spend',
        :'impressions' => :'impressions',
        :'inline_link_clicks' => :'inline_link_clicks',
        :'counted_arrivals' => :'counted_arrivals',
        :'recorded_conversions' => :'recorded_conversions',
        :'admitted_conversions' => :'admitted_conversions'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'date' => :'Date',
        :'ad_test_member_id' => :'String',
        :'ad_id' => :'String',
        :'spend_minor' => :'String',
        :'spend' => :'String',
        :'impressions' => :'Integer',
        :'inline_link_clicks' => :'Integer',
        :'counted_arrivals' => :'Integer',
        :'recorded_conversions' => :'Integer',
        :'admitted_conversions' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'spend',
        :'impressions',
        :'inline_link_clicks',
        :'counted_arrivals',
        :'recorded_conversions',
        :'admitted_conversions'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::AdTestCreateReadTestVerdictDailyFactsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::AdTestCreateReadTestVerdictDailyFactsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'ad_test_member_id')
        self.ad_test_member_id = attributes[:'ad_test_member_id']
      else
        self.ad_test_member_id = nil
      end

      if attributes.key?(:'ad_id')
        self.ad_id = attributes[:'ad_id']
      else
        self.ad_id = nil
      end

      if attributes.key?(:'spend_minor')
        self.spend_minor = attributes[:'spend_minor']
      else
        self.spend_minor = nil
      end

      if attributes.key?(:'spend')
        self.spend = attributes[:'spend']
      else
        self.spend = nil
      end

      if attributes.key?(:'impressions')
        self.impressions = attributes[:'impressions']
      else
        self.impressions = nil
      end

      if attributes.key?(:'inline_link_clicks')
        self.inline_link_clicks = attributes[:'inline_link_clicks']
      end

      if attributes.key?(:'counted_arrivals')
        self.counted_arrivals = attributes[:'counted_arrivals']
      else
        self.counted_arrivals = nil
      end

      if attributes.key?(:'recorded_conversions')
        self.recorded_conversions = attributes[:'recorded_conversions']
      else
        self.recorded_conversions = nil
      end

      if attributes.key?(:'admitted_conversions')
        self.admitted_conversions = attributes[:'admitted_conversions']
      else
        self.admitted_conversions = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @date.nil?
        invalid_properties.push('invalid value for "date", date cannot be nil.')
      end

      if @ad_test_member_id.nil?
        invalid_properties.push('invalid value for "ad_test_member_id", ad_test_member_id cannot be nil.')
      end

      if @ad_test_member_id.to_s.length > 26
        invalid_properties.push('invalid value for "ad_test_member_id", the character length must be smaller than or equal to 26.')
      end

      if @ad_test_member_id.to_s.length < 26
        invalid_properties.push('invalid value for "ad_test_member_id", the character length must be greater than or equal to 26.')
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if @ad_test_member_id !~ pattern
        invalid_properties.push("invalid value for \"ad_test_member_id\", must conform to the pattern #{pattern}.")
      end

      if @ad_id.nil?
        invalid_properties.push('invalid value for "ad_id", ad_id cannot be nil.')
      end

      if @ad_id.to_s.length > 128
        invalid_properties.push('invalid value for "ad_id", the character length must be smaller than or equal to 128.')
      end

      pattern = Regexp.new(/^[0-9]+$/)
      if @ad_id !~ pattern
        invalid_properties.push("invalid value for \"ad_id\", must conform to the pattern #{pattern}.")
      end

      if @spend_minor.nil?
        invalid_properties.push('invalid value for "spend_minor", spend_minor cannot be nil.')
      end

      pattern = Regexp.new(/^[0-9]+(?:\.[0-9]+)?$/)
      if @spend_minor !~ pattern
        invalid_properties.push("invalid value for \"spend_minor\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @date.nil?
      return false if @ad_test_member_id.nil?
      return false if @ad_test_member_id.to_s.length > 26
      return false if @ad_test_member_id.to_s.length < 26
      return false if @ad_test_member_id !~ Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      return false if @ad_id.nil?
      return false if @ad_id.to_s.length > 128
      return false if @ad_id !~ Regexp.new(/^[0-9]+$/)
      return false if @spend_minor.nil?
      return false if @spend_minor !~ Regexp.new(/^[0-9]+(?:\.[0-9]+)?$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] date Value to be assigned
    def date=(date)
      if date.nil?
        fail ArgumentError, 'date cannot be nil'
      end

      @date = date
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_test_member_id Value to be assigned
    def ad_test_member_id=(ad_test_member_id)
      if ad_test_member_id.nil?
        fail ArgumentError, 'ad_test_member_id cannot be nil'
      end

      if ad_test_member_id.to_s.length > 26
        fail ArgumentError, 'invalid value for "ad_test_member_id", the character length must be smaller than or equal to 26.'
      end

      if ad_test_member_id.to_s.length < 26
        fail ArgumentError, 'invalid value for "ad_test_member_id", the character length must be greater than or equal to 26.'
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if ad_test_member_id !~ pattern
        fail ArgumentError, "invalid value for \"ad_test_member_id\", must conform to the pattern #{pattern}."
      end

      @ad_test_member_id = ad_test_member_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_id Value to be assigned
    def ad_id=(ad_id)
      if ad_id.nil?
        fail ArgumentError, 'ad_id cannot be nil'
      end

      if ad_id.to_s.length > 128
        fail ArgumentError, 'invalid value for "ad_id", the character length must be smaller than or equal to 128.'
      end

      pattern = Regexp.new(/^[0-9]+$/)
      if ad_id !~ pattern
        fail ArgumentError, "invalid value for \"ad_id\", must conform to the pattern #{pattern}."
      end

      @ad_id = ad_id
    end

    # Custom attribute writer method with validation
    # @param [Object] spend_minor Value to be assigned
    def spend_minor=(spend_minor)
      if spend_minor.nil?
        fail ArgumentError, 'spend_minor cannot be nil'
      end

      pattern = Regexp.new(/^[0-9]+(?:\.[0-9]+)?$/)
      if spend_minor !~ pattern
        fail ArgumentError, "invalid value for \"spend_minor\", must conform to the pattern #{pattern}."
      end

      @spend_minor = spend_minor
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          date == o.date &&
          ad_test_member_id == o.ad_test_member_id &&
          ad_id == o.ad_id &&
          spend_minor == o.spend_minor &&
          spend == o.spend &&
          impressions == o.impressions &&
          inline_link_clicks == o.inline_link_clicks &&
          counted_arrivals == o.counted_arrivals &&
          recorded_conversions == o.recorded_conversions &&
          admitted_conversions == o.admitted_conversions
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [date, ad_test_member_id, ad_id, spend_minor, spend, impressions, inline_link_clicks, counted_arrivals, recorded_conversions, admitted_conversions].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
