=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class CreateEventRequestAnyOf < ApiModelBase
    # Caller-supplied idempotency key; maximum 128 characters.
    attr_accessor :event_id

    # Signal event name; maximum 100 characters.
    attr_accessor :event_name

    # Optional parent event id; maximum 128 characters.
    attr_accessor :parent_event_id

    attr_accessor :event_time

    # Optional absolute source URL.
    attr_accessor :event_source

    # Optional action source; defaults to website and is limited to 50 characters.
    attr_accessor :action_source

    # Optional visitor identifier; maximum 255 characters.
    attr_accessor :visitor_id

    # Legal basis for processing. Legitimate-interest revenue lifecycle events are rejected; use an authenticated server adapter.
    attr_accessor :consent_basis

    # Consent state supplied with the event.
    attr_accessor :consent

    # Consent Mode v2 signal values supplied with the event.
    attr_accessor :consent_mode

    # TCF v2 data containing string and optional captured_at.
    attr_accessor :tcf

    # Identity fields accepted by the tracker.
    attr_accessor :user_data

    # Advertising click identifiers.
    attr_accessor :click_ids

    attr_accessor :value_data

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'event_id' => :'event_id',
        :'event_name' => :'event_name',
        :'parent_event_id' => :'parent_event_id',
        :'event_time' => :'event_time',
        :'event_source' => :'event_source',
        :'action_source' => :'action_source',
        :'visitor_id' => :'visitor_id',
        :'consent_basis' => :'consent_basis',
        :'consent' => :'consent',
        :'consent_mode' => :'consent_mode',
        :'tcf' => :'tcf',
        :'user_data' => :'user_data',
        :'click_ids' => :'click_ids',
        :'value_data' => :'value_data'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'event_id' => :'String',
        :'event_name' => :'String',
        :'parent_event_id' => :'String',
        :'event_time' => :'CreateEventRequestAnyOfEventTime',
        :'event_source' => :'String',
        :'action_source' => :'String',
        :'visitor_id' => :'String',
        :'consent_basis' => :'String',
        :'consent' => :'Hash<String, Object>',
        :'consent_mode' => :'Hash<String, Object>',
        :'tcf' => :'Hash<String, Object>',
        :'user_data' => :'Hash<String, Object>',
        :'click_ids' => :'Hash<String, Object>',
        :'value_data' => :'CreateEventRequestAnyOfValueData'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::CreateEventRequestAnyOf` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::CreateEventRequestAnyOf`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'event_id')
        self.event_id = attributes[:'event_id']
      end

      if attributes.key?(:'event_name')
        self.event_name = attributes[:'event_name']
      else
        self.event_name = nil
      end

      if attributes.key?(:'parent_event_id')
        self.parent_event_id = attributes[:'parent_event_id']
      end

      if attributes.key?(:'event_time')
        self.event_time = attributes[:'event_time']
      end

      if attributes.key?(:'event_source')
        self.event_source = attributes[:'event_source']
      end

      if attributes.key?(:'action_source')
        self.action_source = attributes[:'action_source']
      end

      if attributes.key?(:'visitor_id')
        self.visitor_id = attributes[:'visitor_id']
      end

      if attributes.key?(:'consent_basis')
        self.consent_basis = attributes[:'consent_basis']
      else
        self.consent_basis = nil
      end

      if attributes.key?(:'consent')
        if (value = attributes[:'consent']).is_a?(Hash)
          self.consent = value
        end
      end

      if attributes.key?(:'consent_mode')
        if (value = attributes[:'consent_mode']).is_a?(Hash)
          self.consent_mode = value
        end
      end

      if attributes.key?(:'tcf')
        if (value = attributes[:'tcf']).is_a?(Hash)
          self.tcf = value
        end
      end

      if attributes.key?(:'user_data')
        if (value = attributes[:'user_data']).is_a?(Hash)
          self.user_data = value
        end
      end

      if attributes.key?(:'click_ids')
        if (value = attributes[:'click_ids']).is_a?(Hash)
          self.click_ids = value
        end
      end

      if attributes.key?(:'value_data')
        self.value_data = attributes[:'value_data']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @event_name.nil?
        invalid_properties.push('invalid value for "event_name", event_name cannot be nil.')
      end

      if @consent_basis.nil?
        invalid_properties.push('invalid value for "consent_basis", consent_basis cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @event_name.nil?
      return false if @consent_basis.nil?
      consent_basis_validator = EnumAttributeValidator.new('String', ["consent"])
      return false unless consent_basis_validator.valid?(@consent_basis)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] event_name Value to be assigned
    def event_name=(event_name)
      if event_name.nil?
        fail ArgumentError, 'event_name cannot be nil'
      end

      @event_name = event_name
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] consent_basis Object to be assigned
    def consent_basis=(consent_basis)
      validator = EnumAttributeValidator.new('String', ["consent"])
      unless validator.valid?(consent_basis)
        fail ArgumentError, "invalid value for \"consent_basis\", must be one of #{validator.allowable_values}."
      end
      @consent_basis = consent_basis
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          event_id == o.event_id &&
          event_name == o.event_name &&
          parent_event_id == o.parent_event_id &&
          event_time == o.event_time &&
          event_source == o.event_source &&
          action_source == o.action_source &&
          visitor_id == o.visitor_id &&
          consent_basis == o.consent_basis &&
          consent == o.consent &&
          consent_mode == o.consent_mode &&
          tcf == o.tcf &&
          user_data == o.user_data &&
          click_ids == o.click_ids &&
          value_data == o.value_data
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [event_id, event_name, parent_event_id, event_time, event_source, action_source, visitor_id, consent_basis, consent, consent_mode, tcf, user_data, click_ids, value_data].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
