=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class CreativeIntakeReadCreative < ApiModelBase
    attr_accessor :id

    attr_accessor :fingerprint

    attr_accessor :type

    attr_accessor :mime_type

    attr_accessor :byte_size

    attr_accessor :width

    attr_accessor :height

    attr_accessor :aspect_ratio

    attr_accessor :duration_ms

    attr_accessor :original_filename

    attr_accessor :source_ref

    attr_accessor :tags

    attr_accessor :status

    attr_accessor :created_at

    attr_accessor :updated_at

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'fingerprint' => :'fingerprint',
        :'type' => :'type',
        :'mime_type' => :'mime_type',
        :'byte_size' => :'byte_size',
        :'width' => :'width',
        :'height' => :'height',
        :'aspect_ratio' => :'aspect_ratio',
        :'duration_ms' => :'duration_ms',
        :'original_filename' => :'original_filename',
        :'source_ref' => :'source_ref',
        :'tags' => :'tags',
        :'status' => :'status',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'fingerprint' => :'String',
        :'type' => :'String',
        :'mime_type' => :'String',
        :'byte_size' => :'Integer',
        :'width' => :'Integer',
        :'height' => :'Integer',
        :'aspect_ratio' => :'Float',
        :'duration_ms' => :'Integer',
        :'original_filename' => :'String',
        :'source_ref' => :'String',
        :'tags' => :'CreativeIntakeReadCreativeTags',
        :'status' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'width',
        :'height',
        :'aspect_ratio',
        :'duration_ms',
        :'original_filename',
        :'source_ref',
        :'created_at',
        :'updated_at'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::CreativeIntakeReadCreative` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::CreativeIntakeReadCreative`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'fingerprint')
        self.fingerprint = attributes[:'fingerprint']
      else
        self.fingerprint = nil
      end

      if attributes.key?(:'type')
        self.type = attributes[:'type']
      else
        self.type = nil
      end

      if attributes.key?(:'mime_type')
        self.mime_type = attributes[:'mime_type']
      else
        self.mime_type = nil
      end

      if attributes.key?(:'byte_size')
        self.byte_size = attributes[:'byte_size']
      else
        self.byte_size = nil
      end

      if attributes.key?(:'width')
        self.width = attributes[:'width']
      else
        self.width = nil
      end

      if attributes.key?(:'height')
        self.height = attributes[:'height']
      else
        self.height = nil
      end

      if attributes.key?(:'aspect_ratio')
        self.aspect_ratio = attributes[:'aspect_ratio']
      else
        self.aspect_ratio = nil
      end

      if attributes.key?(:'duration_ms')
        self.duration_ms = attributes[:'duration_ms']
      else
        self.duration_ms = nil
      end

      if attributes.key?(:'original_filename')
        self.original_filename = attributes[:'original_filename']
      end

      if attributes.key?(:'source_ref')
        self.source_ref = attributes[:'source_ref']
      else
        self.source_ref = nil
      end

      if attributes.key?(:'tags')
        self.tags = attributes[:'tags']
      else
        self.tags = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if @id !~ pattern
        invalid_properties.push("invalid value for \"id\", must conform to the pattern #{pattern}.")
      end

      if @fingerprint.nil?
        invalid_properties.push('invalid value for "fingerprint", fingerprint cannot be nil.')
      end

      if @type.nil?
        invalid_properties.push('invalid value for "type", type cannot be nil.')
      end

      if @mime_type.nil?
        invalid_properties.push('invalid value for "mime_type", mime_type cannot be nil.')
      end

      if @byte_size.nil?
        invalid_properties.push('invalid value for "byte_size", byte_size cannot be nil.')
      end

      if @tags.nil?
        invalid_properties.push('invalid value for "tags", tags cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @id !~ Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      return false if @fingerprint.nil?
      return false if @type.nil?
      type_validator = EnumAttributeValidator.new('String', ["image", "video"])
      return false unless type_validator.valid?(@type)
      return false if @mime_type.nil?
      return false if @byte_size.nil?
      return false if @tags.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["draft", "approved", "retired"])
      return false unless status_validator.valid?(@status)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if id !~ pattern
        fail ArgumentError, "invalid value for \"id\", must conform to the pattern #{pattern}."
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] fingerprint Value to be assigned
    def fingerprint=(fingerprint)
      if fingerprint.nil?
        fail ArgumentError, 'fingerprint cannot be nil'
      end

      @fingerprint = fingerprint
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] type Object to be assigned
    def type=(type)
      validator = EnumAttributeValidator.new('String', ["image", "video"])
      unless validator.valid?(type)
        fail ArgumentError, "invalid value for \"type\", must be one of #{validator.allowable_values}."
      end
      @type = type
    end

    # Custom attribute writer method with validation
    # @param [Object] mime_type Value to be assigned
    def mime_type=(mime_type)
      if mime_type.nil?
        fail ArgumentError, 'mime_type cannot be nil'
      end

      @mime_type = mime_type
    end

    # Custom attribute writer method with validation
    # @param [Object] byte_size Value to be assigned
    def byte_size=(byte_size)
      if byte_size.nil?
        fail ArgumentError, 'byte_size cannot be nil'
      end

      @byte_size = byte_size
    end

    # Custom attribute writer method with validation
    # @param [Object] tags Value to be assigned
    def tags=(tags)
      if tags.nil?
        fail ArgumentError, 'tags cannot be nil'
      end

      @tags = tags
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["draft", "approved", "retired"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          fingerprint == o.fingerprint &&
          type == o.type &&
          mime_type == o.mime_type &&
          byte_size == o.byte_size &&
          width == o.width &&
          height == o.height &&
          aspect_ratio == o.aspect_ratio &&
          duration_ms == o.duration_ms &&
          original_filename == o.original_filename &&
          source_ref == o.source_ref &&
          tags == o.tags &&
          status == o.status &&
          created_at == o.created_at &&
          updated_at == o.updated_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, fingerprint, type, mime_type, byte_size, width, height, aspect_ratio, duration_ms, original_filename, source_ref, tags, status, created_at, updated_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
