=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class DeleteUserData200Response < ApiModelBase
    attr_accessor :deletion_request_id

    attr_accessor :duplicate

    attr_accessor :events_updated

    attr_accessor :sessions_updated

    attr_accessor :completed_at

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'deletion_request_id' => :'deletion_request_id',
        :'duplicate' => :'duplicate',
        :'events_updated' => :'events_updated',
        :'sessions_updated' => :'sessions_updated',
        :'completed_at' => :'completed_at'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'deletion_request_id' => :'String',
        :'duplicate' => :'Boolean',
        :'events_updated' => :'Integer',
        :'sessions_updated' => :'Integer',
        :'completed_at' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::DeleteUserData200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::DeleteUserData200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'deletion_request_id')
        self.deletion_request_id = attributes[:'deletion_request_id']
      else
        self.deletion_request_id = nil
      end

      if attributes.key?(:'duplicate')
        self.duplicate = attributes[:'duplicate']
      else
        self.duplicate = nil
      end

      if attributes.key?(:'events_updated')
        self.events_updated = attributes[:'events_updated']
      else
        self.events_updated = nil
      end

      if attributes.key?(:'sessions_updated')
        self.sessions_updated = attributes[:'sessions_updated']
      else
        self.sessions_updated = nil
      end

      if attributes.key?(:'completed_at')
        self.completed_at = attributes[:'completed_at']
      else
        self.completed_at = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @deletion_request_id.nil?
        invalid_properties.push('invalid value for "deletion_request_id", deletion_request_id cannot be nil.')
      end

      if @duplicate.nil?
        invalid_properties.push('invalid value for "duplicate", duplicate cannot be nil.')
      end

      if @events_updated.nil?
        invalid_properties.push('invalid value for "events_updated", events_updated cannot be nil.')
      end

      if @sessions_updated.nil?
        invalid_properties.push('invalid value for "sessions_updated", sessions_updated cannot be nil.')
      end

      if @completed_at.nil?
        invalid_properties.push('invalid value for "completed_at", completed_at cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @deletion_request_id.nil?
      return false if @duplicate.nil?
      return false if @events_updated.nil?
      return false if @sessions_updated.nil?
      return false if @completed_at.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] deletion_request_id Value to be assigned
    def deletion_request_id=(deletion_request_id)
      if deletion_request_id.nil?
        fail ArgumentError, 'deletion_request_id cannot be nil'
      end

      @deletion_request_id = deletion_request_id
    end

    # Custom attribute writer method with validation
    # @param [Object] duplicate Value to be assigned
    def duplicate=(duplicate)
      if duplicate.nil?
        fail ArgumentError, 'duplicate cannot be nil'
      end

      @duplicate = duplicate
    end

    # Custom attribute writer method with validation
    # @param [Object] events_updated Value to be assigned
    def events_updated=(events_updated)
      if events_updated.nil?
        fail ArgumentError, 'events_updated cannot be nil'
      end

      @events_updated = events_updated
    end

    # Custom attribute writer method with validation
    # @param [Object] sessions_updated Value to be assigned
    def sessions_updated=(sessions_updated)
      if sessions_updated.nil?
        fail ArgumentError, 'sessions_updated cannot be nil'
      end

      @sessions_updated = sessions_updated
    end

    # Custom attribute writer method with validation
    # @param [Object] completed_at Value to be assigned
    def completed_at=(completed_at)
      if completed_at.nil?
        fail ArgumentError, 'completed_at cannot be nil'
      end

      @completed_at = completed_at
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          deletion_request_id == o.deletion_request_id &&
          duplicate == o.duplicate &&
          events_updated == o.events_updated &&
          sessions_updated == o.sessions_updated &&
          completed_at == o.completed_at
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [deletion_request_id, duplicate, events_updated, sessions_updated, completed_at].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
