=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class DeploymentPlan < ApiModelBase
    attr_accessor :id

    attr_accessor :workspace_id

    attr_accessor :platform_ad_account_id

    attr_accessor :platform

    attr_accessor :campaign_ref

    attr_accessor :campaign_spec

    attr_accessor :ad_set_ref

    # When present, bid_amount must be a positive integer in Meta minor units for the account currency. Digit-only strings of at most 18 digits are accepted and normalized to integers. Null, zero, negatives, decimals and other strings are refused on ad_set_spec.bid_amount.
    attr_accessor :ad_set_spec

    attr_accessor :budget_type

    attr_accessor :budget_amount_minor

    attr_accessor :currency

    attr_accessor :copy

    attr_accessor :landing_page

    attr_accessor :utm_policy_id

    attr_accessor :naming_policy_id

    attr_accessor :status

    attr_accessor :validation_result

    attr_accessor :diff

    attr_accessor :validated_at

    attr_accessor :approval_id

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :platform_object_ids

    attr_accessor :name

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'workspace_id' => :'workspace_id',
        :'platform_ad_account_id' => :'platform_ad_account_id',
        :'platform' => :'platform',
        :'campaign_ref' => :'campaign_ref',
        :'campaign_spec' => :'campaign_spec',
        :'ad_set_ref' => :'ad_set_ref',
        :'ad_set_spec' => :'ad_set_spec',
        :'budget_type' => :'budget_type',
        :'budget_amount_minor' => :'budget_amount_minor',
        :'currency' => :'currency',
        :'copy' => :'copy',
        :'landing_page' => :'landing_page',
        :'utm_policy_id' => :'utm_policy_id',
        :'naming_policy_id' => :'naming_policy_id',
        :'status' => :'status',
        :'validation_result' => :'validation_result',
        :'diff' => :'diff',
        :'validated_at' => :'validated_at',
        :'approval_id' => :'approval_id',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'platform_object_ids' => :'platform_object_ids',
        :'name' => :'name'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'workspace_id' => :'Integer',
        :'platform_ad_account_id' => :'Integer',
        :'platform' => :'String',
        :'campaign_ref' => :'String',
        :'campaign_spec' => :'Array<Object>',
        :'ad_set_ref' => :'String',
        :'ad_set_spec' => :'Array<Object>',
        :'budget_type' => :'String',
        :'budget_amount_minor' => :'Integer',
        :'currency' => :'String',
        :'copy' => :'Array<Object>',
        :'landing_page' => :'String',
        :'utm_policy_id' => :'String',
        :'naming_policy_id' => :'String',
        :'status' => :'String',
        :'validation_result' => :'Array<Object>',
        :'diff' => :'Array<Object>',
        :'validated_at' => :'Time',
        :'approval_id' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'platform_object_ids' => :'Array<Object>',
        :'name' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'campaign_ref',
        :'campaign_spec',
        :'ad_set_ref',
        :'ad_set_spec',
        :'utm_policy_id',
        :'naming_policy_id',
        :'validation_result',
        :'diff',
        :'validated_at',
        :'approval_id',
        :'created_at',
        :'updated_at',
        :'name'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::DeploymentPlan` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::DeploymentPlan`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'workspace_id')
        self.workspace_id = attributes[:'workspace_id']
      else
        self.workspace_id = nil
      end

      if attributes.key?(:'platform_ad_account_id')
        self.platform_ad_account_id = attributes[:'platform_ad_account_id']
      else
        self.platform_ad_account_id = nil
      end

      if attributes.key?(:'platform')
        self.platform = attributes[:'platform']
      else
        self.platform = nil
      end

      if attributes.key?(:'campaign_ref')
        self.campaign_ref = attributes[:'campaign_ref']
      else
        self.campaign_ref = nil
      end

      if attributes.key?(:'campaign_spec')
        if (value = attributes[:'campaign_spec']).is_a?(Array)
          self.campaign_spec = value
        end
      else
        self.campaign_spec = nil
      end

      if attributes.key?(:'ad_set_ref')
        self.ad_set_ref = attributes[:'ad_set_ref']
      else
        self.ad_set_ref = nil
      end

      if attributes.key?(:'ad_set_spec')
        if (value = attributes[:'ad_set_spec']).is_a?(Array)
          self.ad_set_spec = value
        end
      else
        self.ad_set_spec = nil
      end

      if attributes.key?(:'budget_type')
        self.budget_type = attributes[:'budget_type']
      else
        self.budget_type = nil
      end

      if attributes.key?(:'budget_amount_minor')
        self.budget_amount_minor = attributes[:'budget_amount_minor']
      else
        self.budget_amount_minor = nil
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      else
        self.currency = nil
      end

      if attributes.key?(:'copy')
        if (value = attributes[:'copy']).is_a?(Array)
          self.copy = value
        end
      else
        self.copy = nil
      end

      if attributes.key?(:'landing_page')
        self.landing_page = attributes[:'landing_page']
      else
        self.landing_page = nil
      end

      if attributes.key?(:'utm_policy_id')
        self.utm_policy_id = attributes[:'utm_policy_id']
      else
        self.utm_policy_id = nil
      end

      if attributes.key?(:'naming_policy_id')
        self.naming_policy_id = attributes[:'naming_policy_id']
      else
        self.naming_policy_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'validation_result')
        if (value = attributes[:'validation_result']).is_a?(Array)
          self.validation_result = value
        end
      else
        self.validation_result = nil
      end

      if attributes.key?(:'diff')
        if (value = attributes[:'diff']).is_a?(Array)
          self.diff = value
        end
      else
        self.diff = nil
      end

      if attributes.key?(:'validated_at')
        self.validated_at = attributes[:'validated_at']
      else
        self.validated_at = nil
      end

      if attributes.key?(:'approval_id')
        self.approval_id = attributes[:'approval_id']
      else
        self.approval_id = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'platform_object_ids')
        if (value = attributes[:'platform_object_ids']).is_a?(Array)
          self.platform_object_ids = value
        end
      else
        self.platform_object_ids = nil
      end

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      else
        self.name = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @workspace_id.nil?
        invalid_properties.push('invalid value for "workspace_id", workspace_id cannot be nil.')
      end

      if @platform_ad_account_id.nil?
        invalid_properties.push('invalid value for "platform_ad_account_id", platform_ad_account_id cannot be nil.')
      end

      if @platform.nil?
        invalid_properties.push('invalid value for "platform", platform cannot be nil.')
      end

      if @budget_type.nil?
        invalid_properties.push('invalid value for "budget_type", budget_type cannot be nil.')
      end

      if @budget_amount_minor.nil?
        invalid_properties.push('invalid value for "budget_amount_minor", budget_amount_minor cannot be nil.')
      end

      if @currency.nil?
        invalid_properties.push('invalid value for "currency", currency cannot be nil.')
      end

      if @copy.nil?
        invalid_properties.push('invalid value for "copy", copy cannot be nil.')
      end

      if @landing_page.nil?
        invalid_properties.push('invalid value for "landing_page", landing_page cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @platform_object_ids.nil?
        invalid_properties.push('invalid value for "platform_object_ids", platform_object_ids cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @workspace_id.nil?
      return false if @platform_ad_account_id.nil?
      return false if @platform.nil?
      return false if @budget_type.nil?
      return false if @budget_amount_minor.nil?
      return false if @currency.nil?
      return false if @copy.nil?
      return false if @landing_page.nil?
      return false if @status.nil?
      return false if @platform_object_ids.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] workspace_id Value to be assigned
    def workspace_id=(workspace_id)
      if workspace_id.nil?
        fail ArgumentError, 'workspace_id cannot be nil'
      end

      @workspace_id = workspace_id
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_ad_account_id Value to be assigned
    def platform_ad_account_id=(platform_ad_account_id)
      if platform_ad_account_id.nil?
        fail ArgumentError, 'platform_ad_account_id cannot be nil'
      end

      @platform_ad_account_id = platform_ad_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] platform Value to be assigned
    def platform=(platform)
      if platform.nil?
        fail ArgumentError, 'platform cannot be nil'
      end

      @platform = platform
    end

    # Custom attribute writer method with validation
    # @param [Object] budget_type Value to be assigned
    def budget_type=(budget_type)
      if budget_type.nil?
        fail ArgumentError, 'budget_type cannot be nil'
      end

      @budget_type = budget_type
    end

    # Custom attribute writer method with validation
    # @param [Object] budget_amount_minor Value to be assigned
    def budget_amount_minor=(budget_amount_minor)
      if budget_amount_minor.nil?
        fail ArgumentError, 'budget_amount_minor cannot be nil'
      end

      @budget_amount_minor = budget_amount_minor
    end

    # Custom attribute writer method with validation
    # @param [Object] currency Value to be assigned
    def currency=(currency)
      if currency.nil?
        fail ArgumentError, 'currency cannot be nil'
      end

      @currency = currency
    end

    # Custom attribute writer method with validation
    # @param [Object] copy Value to be assigned
    def copy=(copy)
      if copy.nil?
        fail ArgumentError, 'copy cannot be nil'
      end

      @copy = copy
    end

    # Custom attribute writer method with validation
    # @param [Object] landing_page Value to be assigned
    def landing_page=(landing_page)
      if landing_page.nil?
        fail ArgumentError, 'landing_page cannot be nil'
      end

      @landing_page = landing_page
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_object_ids Value to be assigned
    def platform_object_ids=(platform_object_ids)
      if platform_object_ids.nil?
        fail ArgumentError, 'platform_object_ids cannot be nil'
      end

      @platform_object_ids = platform_object_ids
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          workspace_id == o.workspace_id &&
          platform_ad_account_id == o.platform_ad_account_id &&
          platform == o.platform &&
          campaign_ref == o.campaign_ref &&
          campaign_spec == o.campaign_spec &&
          ad_set_ref == o.ad_set_ref &&
          ad_set_spec == o.ad_set_spec &&
          budget_type == o.budget_type &&
          budget_amount_minor == o.budget_amount_minor &&
          currency == o.currency &&
          copy == o.copy &&
          landing_page == o.landing_page &&
          utm_policy_id == o.utm_policy_id &&
          naming_policy_id == o.naming_policy_id &&
          status == o.status &&
          validation_result == o.validation_result &&
          diff == o.diff &&
          validated_at == o.validated_at &&
          approval_id == o.approval_id &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          platform_object_ids == o.platform_object_ids &&
          name == o.name
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, workspace_id, platform_ad_account_id, platform, campaign_ref, campaign_spec, ad_set_ref, ad_set_spec, budget_type, budget_amount_minor, currency, copy, landing_page, utm_policy_id, naming_policy_id, status, validation_result, diff, validated_at, approval_id, created_at, updated_at, platform_object_ids, name].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
