=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  # Optional complete per-ad copy override; null uses the plan copy.
  class DeploymentPlanReadCreativesInnerCopy < ApiModelBase
    attr_accessor :primary_text

    attr_accessor :headline

    attr_accessor :description

    attr_accessor :cta

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'primary_text' => :'primary_text',
        :'headline' => :'headline',
        :'description' => :'description',
        :'cta' => :'cta'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'primary_text' => :'String',
        :'headline' => :'String',
        :'description' => :'String',
        :'cta' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::DeploymentPlanReadCreativesInnerCopy` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::DeploymentPlanReadCreativesInnerCopy`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'primary_text')
        self.primary_text = attributes[:'primary_text']
      else
        self.primary_text = nil
      end

      if attributes.key?(:'headline')
        self.headline = attributes[:'headline']
      else
        self.headline = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'cta')
        self.cta = attributes[:'cta']
      else
        self.cta = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @primary_text.nil?
        invalid_properties.push('invalid value for "primary_text", primary_text cannot be nil.')
      end

      if @headline.nil?
        invalid_properties.push('invalid value for "headline", headline cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @cta.nil?
        invalid_properties.push('invalid value for "cta", cta cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @primary_text.nil?
      return false if @headline.nil?
      return false if @description.nil?
      return false if @cta.nil?
      cta_validator = EnumAttributeValidator.new('String', ["learn_more", "shop_now", "sign_up"])
      return false unless cta_validator.valid?(@cta)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] primary_text Value to be assigned
    def primary_text=(primary_text)
      if primary_text.nil?
        fail ArgumentError, 'primary_text cannot be nil'
      end

      @primary_text = primary_text
    end

    # Custom attribute writer method with validation
    # @param [Object] headline Value to be assigned
    def headline=(headline)
      if headline.nil?
        fail ArgumentError, 'headline cannot be nil'
      end

      @headline = headline
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      @description = description
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] cta Object to be assigned
    def cta=(cta)
      validator = EnumAttributeValidator.new('String', ["learn_more", "shop_now", "sign_up"])
      unless validator.valid?(cta)
        fail ArgumentError, "invalid value for \"cta\", must be one of #{validator.allowable_values}."
      end
      @cta = cta
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          primary_text == o.primary_text &&
          headline == o.headline &&
          description == o.description &&
          cta == o.cta
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [primary_text, headline, description, cta].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
