=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class DeploymentPlanRead < ApiModelBase
    attr_accessor :name

    attr_accessor :id

    attr_accessor :platform_ad_account_id

    # Current review version. Pass this value when executing the plan you reviewed.
    attr_accessor :review_version

    attr_accessor :copy

    attr_accessor :landing_page

    attr_accessor :creatives

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'name' => :'name',
        :'id' => :'id',
        :'platform_ad_account_id' => :'platform_ad_account_id',
        :'review_version' => :'review_version',
        :'copy' => :'copy',
        :'landing_page' => :'landing_page',
        :'creatives' => :'creatives'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'name' => :'String',
        :'id' => :'String',
        :'platform_ad_account_id' => :'Integer',
        :'review_version' => :'String',
        :'copy' => :'DeploymentPlanReadCopy',
        :'landing_page' => :'String',
        :'creatives' => :'Array<DeploymentPlanReadCreativesInner>'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'name',
        :'copy',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::DeploymentPlanRead` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::DeploymentPlanRead`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'name')
        self.name = attributes[:'name']
      end

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'platform_ad_account_id')
        self.platform_ad_account_id = attributes[:'platform_ad_account_id']
      else
        self.platform_ad_account_id = nil
      end

      if attributes.key?(:'review_version')
        self.review_version = attributes[:'review_version']
      else
        self.review_version = nil
      end

      if attributes.key?(:'copy')
        self.copy = attributes[:'copy']
      end

      if attributes.key?(:'landing_page')
        self.landing_page = attributes[:'landing_page']
      end

      if attributes.key?(:'creatives')
        if (value = attributes[:'creatives']).is_a?(Array)
          self.creatives = value
        end
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @platform_ad_account_id.nil?
        invalid_properties.push('invalid value for "platform_ad_account_id", platform_ad_account_id cannot be nil.')
      end

      if @review_version.nil?
        invalid_properties.push('invalid value for "review_version", review_version cannot be nil.')
      end

      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if @review_version !~ pattern
        invalid_properties.push("invalid value for \"review_version\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @platform_ad_account_id.nil?
      return false if @review_version.nil?
      return false if @review_version !~ Regexp.new(/^[a-f0-9]{64}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_ad_account_id Value to be assigned
    def platform_ad_account_id=(platform_ad_account_id)
      if platform_ad_account_id.nil?
        fail ArgumentError, 'platform_ad_account_id cannot be nil'
      end

      @platform_ad_account_id = platform_ad_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] review_version Value to be assigned
    def review_version=(review_version)
      if review_version.nil?
        fail ArgumentError, 'review_version cannot be nil'
      end

      pattern = Regexp.new(/^[a-f0-9]{64}$/)
      if review_version !~ pattern
        fail ArgumentError, "invalid value for \"review_version\", must conform to the pattern #{pattern}."
      end

      @review_version = review_version
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          name == o.name &&
          id == o.id &&
          platform_ad_account_id == o.platform_ad_account_id &&
          review_version == o.review_version &&
          copy == o.copy &&
          landing_page == o.landing_page &&
          creatives == o.creatives
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [name, id, platform_ad_account_id, review_version, copy, landing_page, creatives].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
