=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class DestinationStatus
    ACTIVE = "active".freeze
    INACTIVE = "inactive".freeze

    def self.all_vars
      @all_vars ||= [ACTIVE, INACTIVE].freeze
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def self.build_from_hash(value)
      new.build_from_hash(value)
    end

    # Builds the enum from string
    # @param [String] The enum value in the form of the string
    # @return [String] The enum value
    def build_from_hash(value)
      return value if DestinationStatus.all_vars.include?(value)
      raise "Invalid ENUM value #{value} for class #DestinationStatus"
    end
  end
end
