=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class GetEvent200ResponseDeliveriesInner < ApiModelBase
    attr_accessor :id

    attr_accessor :signal_tracker_id

    attr_accessor :event_id

    attr_accessor :destination_id

    attr_accessor :status

    attr_accessor :is_test

    attr_accessor :attempt_count

    attr_accessor :last_error

    attr_accessor :platform_response

    attr_accessor :platform_trace_id

    attr_accessor :next_attempt_at

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :explanation

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'signal_tracker_id' => :'signal_tracker_id',
        :'event_id' => :'event_id',
        :'destination_id' => :'destination_id',
        :'status' => :'status',
        :'is_test' => :'is_test',
        :'attempt_count' => :'attempt_count',
        :'last_error' => :'last_error',
        :'platform_response' => :'platform_response',
        :'platform_trace_id' => :'platform_trace_id',
        :'next_attempt_at' => :'next_attempt_at',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'explanation' => :'explanation'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'signal_tracker_id' => :'String',
        :'event_id' => :'String',
        :'destination_id' => :'String',
        :'status' => :'DeliveryStatus',
        :'is_test' => :'Boolean',
        :'attempt_count' => :'Integer',
        :'last_error' => :'GetEvent200ResponseEventConsent',
        :'platform_response' => :'GetEvent200ResponseEventConsent',
        :'platform_trace_id' => :'String',
        :'next_attempt_at' => :'String',
        :'created_at' => :'String',
        :'updated_at' => :'String',
        :'explanation' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'destination_id',
        :'last_error',
        :'platform_response',
        :'platform_trace_id',
        :'next_attempt_at',
        :'updated_at',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::GetEvent200ResponseDeliveriesInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::GetEvent200ResponseDeliveriesInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'signal_tracker_id')
        self.signal_tracker_id = attributes[:'signal_tracker_id']
      else
        self.signal_tracker_id = nil
      end

      if attributes.key?(:'event_id')
        self.event_id = attributes[:'event_id']
      else
        self.event_id = nil
      end

      if attributes.key?(:'destination_id')
        self.destination_id = attributes[:'destination_id']
      else
        self.destination_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'is_test')
        self.is_test = attributes[:'is_test']
      else
        self.is_test = nil
      end

      if attributes.key?(:'attempt_count')
        self.attempt_count = attributes[:'attempt_count']
      else
        self.attempt_count = nil
      end

      if attributes.key?(:'last_error')
        self.last_error = attributes[:'last_error']
      else
        self.last_error = nil
      end

      if attributes.key?(:'platform_response')
        self.platform_response = attributes[:'platform_response']
      else
        self.platform_response = nil
      end

      if attributes.key?(:'platform_trace_id')
        self.platform_trace_id = attributes[:'platform_trace_id']
      else
        self.platform_trace_id = nil
      end

      if attributes.key?(:'next_attempt_at')
        self.next_attempt_at = attributes[:'next_attempt_at']
      else
        self.next_attempt_at = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'explanation')
        self.explanation = attributes[:'explanation']
      else
        self.explanation = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @signal_tracker_id.nil?
        invalid_properties.push('invalid value for "signal_tracker_id", signal_tracker_id cannot be nil.')
      end

      if @event_id.nil?
        invalid_properties.push('invalid value for "event_id", event_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @is_test.nil?
        invalid_properties.push('invalid value for "is_test", is_test cannot be nil.')
      end

      if @attempt_count.nil?
        invalid_properties.push('invalid value for "attempt_count", attempt_count cannot be nil.')
      end

      if @created_at.nil?
        invalid_properties.push('invalid value for "created_at", created_at cannot be nil.')
      end

      if @explanation.nil?
        invalid_properties.push('invalid value for "explanation", explanation cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @signal_tracker_id.nil?
      return false if @event_id.nil?
      return false if @status.nil?
      return false if @is_test.nil?
      return false if @attempt_count.nil?
      return false if @created_at.nil?
      return false if @explanation.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] signal_tracker_id Value to be assigned
    def signal_tracker_id=(signal_tracker_id)
      if signal_tracker_id.nil?
        fail ArgumentError, 'signal_tracker_id cannot be nil'
      end

      @signal_tracker_id = signal_tracker_id
    end

    # Custom attribute writer method with validation
    # @param [Object] event_id Value to be assigned
    def event_id=(event_id)
      if event_id.nil?
        fail ArgumentError, 'event_id cannot be nil'
      end

      @event_id = event_id
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] is_test Value to be assigned
    def is_test=(is_test)
      if is_test.nil?
        fail ArgumentError, 'is_test cannot be nil'
      end

      @is_test = is_test
    end

    # Custom attribute writer method with validation
    # @param [Object] attempt_count Value to be assigned
    def attempt_count=(attempt_count)
      if attempt_count.nil?
        fail ArgumentError, 'attempt_count cannot be nil'
      end

      @attempt_count = attempt_count
    end

    # Custom attribute writer method with validation
    # @param [Object] created_at Value to be assigned
    def created_at=(created_at)
      if created_at.nil?
        fail ArgumentError, 'created_at cannot be nil'
      end

      @created_at = created_at
    end

    # Custom attribute writer method with validation
    # @param [Object] explanation Value to be assigned
    def explanation=(explanation)
      if explanation.nil?
        fail ArgumentError, 'explanation cannot be nil'
      end

      @explanation = explanation
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          signal_tracker_id == o.signal_tracker_id &&
          event_id == o.event_id &&
          destination_id == o.destination_id &&
          status == o.status &&
          is_test == o.is_test &&
          attempt_count == o.attempt_count &&
          last_error == o.last_error &&
          platform_response == o.platform_response &&
          platform_trace_id == o.platform_trace_id &&
          next_attempt_at == o.next_attempt_at &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          explanation == o.explanation
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, signal_tracker_id, event_id, destination_id, status, is_test, attempt_count, last_error, platform_response, platform_trace_id, next_attempt_at, created_at, updated_at, explanation].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
