=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class GetSandbox200Response < ApiModelBase
    attr_accessor :environment

    attr_accessor :authentication_required

    attr_accessor :account_required

    attr_accessor :production_data

    attr_accessor :persists_data

    attr_accessor :provider_delivery

    attr_accessor :description

    attr_accessor :self_serve_key

    attr_accessor :try

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'environment' => :'environment',
        :'authentication_required' => :'authentication_required',
        :'account_required' => :'account_required',
        :'production_data' => :'production_data',
        :'persists_data' => :'persists_data',
        :'provider_delivery' => :'provider_delivery',
        :'description' => :'description',
        :'self_serve_key' => :'self_serve_key',
        :'try' => :'try'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'environment' => :'String',
        :'authentication_required' => :'Boolean',
        :'account_required' => :'Boolean',
        :'production_data' => :'Boolean',
        :'persists_data' => :'Boolean',
        :'provider_delivery' => :'Boolean',
        :'description' => :'String',
        :'self_serve_key' => :'GetSandbox200ResponseSelfServeKey',
        :'try' => :'GetSandbox200ResponseTry'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::GetSandbox200Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::GetSandbox200Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'environment')
        self.environment = attributes[:'environment']
      else
        self.environment = nil
      end

      if attributes.key?(:'authentication_required')
        self.authentication_required = attributes[:'authentication_required']
      else
        self.authentication_required = nil
      end

      if attributes.key?(:'account_required')
        self.account_required = attributes[:'account_required']
      else
        self.account_required = nil
      end

      if attributes.key?(:'production_data')
        self.production_data = attributes[:'production_data']
      else
        self.production_data = nil
      end

      if attributes.key?(:'persists_data')
        self.persists_data = attributes[:'persists_data']
      else
        self.persists_data = nil
      end

      if attributes.key?(:'provider_delivery')
        self.provider_delivery = attributes[:'provider_delivery']
      else
        self.provider_delivery = nil
      end

      if attributes.key?(:'description')
        self.description = attributes[:'description']
      else
        self.description = nil
      end

      if attributes.key?(:'self_serve_key')
        self.self_serve_key = attributes[:'self_serve_key']
      else
        self.self_serve_key = nil
      end

      if attributes.key?(:'try')
        self.try = attributes[:'try']
      else
        self.try = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @environment.nil?
        invalid_properties.push('invalid value for "environment", environment cannot be nil.')
      end

      if @authentication_required.nil?
        invalid_properties.push('invalid value for "authentication_required", authentication_required cannot be nil.')
      end

      if @account_required.nil?
        invalid_properties.push('invalid value for "account_required", account_required cannot be nil.')
      end

      if @production_data.nil?
        invalid_properties.push('invalid value for "production_data", production_data cannot be nil.')
      end

      if @persists_data.nil?
        invalid_properties.push('invalid value for "persists_data", persists_data cannot be nil.')
      end

      if @provider_delivery.nil?
        invalid_properties.push('invalid value for "provider_delivery", provider_delivery cannot be nil.')
      end

      if @description.nil?
        invalid_properties.push('invalid value for "description", description cannot be nil.')
      end

      if @self_serve_key.nil?
        invalid_properties.push('invalid value for "self_serve_key", self_serve_key cannot be nil.')
      end

      if @try.nil?
        invalid_properties.push('invalid value for "try", try cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @environment.nil?
      return false if @authentication_required.nil?
      return false if @account_required.nil?
      return false if @production_data.nil?
      return false if @persists_data.nil?
      return false if @provider_delivery.nil?
      return false if @description.nil?
      return false if @self_serve_key.nil?
      return false if @try.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] environment Value to be assigned
    def environment=(environment)
      if environment.nil?
        fail ArgumentError, 'environment cannot be nil'
      end

      @environment = environment
    end

    # Custom attribute writer method with validation
    # @param [Object] authentication_required Value to be assigned
    def authentication_required=(authentication_required)
      if authentication_required.nil?
        fail ArgumentError, 'authentication_required cannot be nil'
      end

      @authentication_required = authentication_required
    end

    # Custom attribute writer method with validation
    # @param [Object] account_required Value to be assigned
    def account_required=(account_required)
      if account_required.nil?
        fail ArgumentError, 'account_required cannot be nil'
      end

      @account_required = account_required
    end

    # Custom attribute writer method with validation
    # @param [Object] production_data Value to be assigned
    def production_data=(production_data)
      if production_data.nil?
        fail ArgumentError, 'production_data cannot be nil'
      end

      @production_data = production_data
    end

    # Custom attribute writer method with validation
    # @param [Object] persists_data Value to be assigned
    def persists_data=(persists_data)
      if persists_data.nil?
        fail ArgumentError, 'persists_data cannot be nil'
      end

      @persists_data = persists_data
    end

    # Custom attribute writer method with validation
    # @param [Object] provider_delivery Value to be assigned
    def provider_delivery=(provider_delivery)
      if provider_delivery.nil?
        fail ArgumentError, 'provider_delivery cannot be nil'
      end

      @provider_delivery = provider_delivery
    end

    # Custom attribute writer method with validation
    # @param [Object] description Value to be assigned
    def description=(description)
      if description.nil?
        fail ArgumentError, 'description cannot be nil'
      end

      @description = description
    end

    # Custom attribute writer method with validation
    # @param [Object] self_serve_key Value to be assigned
    def self_serve_key=(self_serve_key)
      if self_serve_key.nil?
        fail ArgumentError, 'self_serve_key cannot be nil'
      end

      @self_serve_key = self_serve_key
    end

    # Custom attribute writer method with validation
    # @param [Object] try Value to be assigned
    def try=(try)
      if try.nil?
        fail ArgumentError, 'try cannot be nil'
      end

      @try = try
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          environment == o.environment &&
          authentication_required == o.authentication_required &&
          account_required == o.account_required &&
          production_data == o.production_data &&
          persists_data == o.persists_data &&
          provider_delivery == o.provider_delivery &&
          description == o.description &&
          self_serve_key == o.self_serve_key &&
          try == o.try
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [environment, authentication_required, account_required, production_data, persists_data, provider_delivery, description, self_serve_key, try].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
