=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class GetInventoryMetrics200ResponseObjectMetricsInner < ApiModelBase
    attr_accessor :level

    attr_accessor :external_id

    attr_accessor :date

    attr_accessor :meta

    attr_accessor :arrivals

    attr_accessor :creative_id

    attr_accessor :generator

    attr_accessor :generator_job

    attr_accessor :parent_creative

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'level' => :'level',
        :'external_id' => :'external_id',
        :'date' => :'date',
        :'meta' => :'meta',
        :'arrivals' => :'arrivals',
        :'creative_id' => :'creative_id',
        :'generator' => :'generator',
        :'generator_job' => :'generator_job',
        :'parent_creative' => :'parent_creative'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'level' => :'String',
        :'external_id' => :'String',
        :'date' => :'String',
        :'meta' => :'GetInventoryMetrics200ResponseObjectMetricsInnerMeta',
        :'arrivals' => :'Integer',
        :'creative_id' => :'String',
        :'generator' => :'String',
        :'generator_job' => :'String',
        :'parent_creative' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'meta',
        :'arrivals',
        :'creative_id',
        :'generator',
        :'generator_job',
        :'parent_creative'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::GetInventoryMetrics200ResponseObjectMetricsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::GetInventoryMetrics200ResponseObjectMetricsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'level')
        self.level = attributes[:'level']
      else
        self.level = nil
      end

      if attributes.key?(:'external_id')
        self.external_id = attributes[:'external_id']
      else
        self.external_id = nil
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'meta')
        self.meta = attributes[:'meta']
      else
        self.meta = nil
      end

      if attributes.key?(:'arrivals')
        self.arrivals = attributes[:'arrivals']
      else
        self.arrivals = nil
      end

      if attributes.key?(:'creative_id')
        self.creative_id = attributes[:'creative_id']
      end

      if attributes.key?(:'generator')
        self.generator = attributes[:'generator']
      end

      if attributes.key?(:'generator_job')
        self.generator_job = attributes[:'generator_job']
      end

      if attributes.key?(:'parent_creative')
        self.parent_creative = attributes[:'parent_creative']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @level.nil?
        invalid_properties.push('invalid value for "level", level cannot be nil.')
      end

      if @external_id.nil?
        invalid_properties.push('invalid value for "external_id", external_id cannot be nil.')
      end

      if @date.nil?
        invalid_properties.push('invalid value for "date", date cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @level.nil?
      level_validator = EnumAttributeValidator.new('String', ["campaign", "adset", "ad"])
      return false unless level_validator.valid?(@level)
      return false if @external_id.nil?
      return false if @date.nil?
      true
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] level Object to be assigned
    def level=(level)
      validator = EnumAttributeValidator.new('String', ["campaign", "adset", "ad"])
      unless validator.valid?(level)
        fail ArgumentError, "invalid value for \"level\", must be one of #{validator.allowable_values}."
      end
      @level = level
    end

    # Custom attribute writer method with validation
    # @param [Object] external_id Value to be assigned
    def external_id=(external_id)
      if external_id.nil?
        fail ArgumentError, 'external_id cannot be nil'
      end

      @external_id = external_id
    end

    # Custom attribute writer method with validation
    # @param [Object] date Value to be assigned
    def date=(date)
      if date.nil?
        fail ArgumentError, 'date cannot be nil'
      end

      @date = date
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          level == o.level &&
          external_id == o.external_id &&
          date == o.date &&
          meta == o.meta &&
          arrivals == o.arrivals &&
          creative_id == o.creative_id &&
          generator == o.generator &&
          generator_job == o.generator_job &&
          parent_creative == o.parent_creative
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [level, external_id, date, meta, arrivals, creative_id, generator, generator_job, parent_creative].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
