=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class GetInventoryMetrics200ResponseMetricsInner < ApiModelBase
    attr_accessor :id

    attr_accessor :platform_ad_account_id

    attr_accessor :ad_external_id

    attr_accessor :campaign_external_id

    attr_accessor :adset_external_id

    attr_accessor :date

    attr_accessor :account_currency

    attr_accessor :spend

    attr_accessor :impressions

    attr_accessor :clicks

    attr_accessor :inline_link_clicks

    attr_accessor :actions

    attr_accessor :action_values

    attr_accessor :fetched_at

    attr_accessor :arrivals

    attr_accessor :creative_id

    attr_accessor :generator

    attr_accessor :generator_job

    attr_accessor :parent_creative

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'platform_ad_account_id' => :'platform_ad_account_id',
        :'ad_external_id' => :'ad_external_id',
        :'campaign_external_id' => :'campaign_external_id',
        :'adset_external_id' => :'adset_external_id',
        :'date' => :'date',
        :'account_currency' => :'account_currency',
        :'spend' => :'spend',
        :'impressions' => :'impressions',
        :'clicks' => :'clicks',
        :'inline_link_clicks' => :'inline_link_clicks',
        :'actions' => :'actions',
        :'action_values' => :'action_values',
        :'fetched_at' => :'fetched_at',
        :'arrivals' => :'arrivals',
        :'creative_id' => :'creative_id',
        :'generator' => :'generator',
        :'generator_job' => :'generator_job',
        :'parent_creative' => :'parent_creative'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'platform_ad_account_id' => :'Integer',
        :'ad_external_id' => :'String',
        :'campaign_external_id' => :'String',
        :'adset_external_id' => :'String',
        :'date' => :'String',
        :'account_currency' => :'String',
        :'spend' => :'String',
        :'impressions' => :'Integer',
        :'clicks' => :'Integer',
        :'inline_link_clicks' => :'Integer',
        :'actions' => :'GetEvent200ResponseEventConsent',
        :'action_values' => :'GetEvent200ResponseEventConsent',
        :'fetched_at' => :'String',
        :'arrivals' => :'Integer',
        :'creative_id' => :'String',
        :'generator' => :'String',
        :'generator_job' => :'String',
        :'parent_creative' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'campaign_external_id',
        :'adset_external_id',
        :'actions',
        :'action_values',
        :'fetched_at',
        :'arrivals',
        :'creative_id',
        :'generator',
        :'generator_job',
        :'parent_creative'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::GetInventoryMetrics200ResponseMetricsInner` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::GetInventoryMetrics200ResponseMetricsInner`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'platform_ad_account_id')
        self.platform_ad_account_id = attributes[:'platform_ad_account_id']
      else
        self.platform_ad_account_id = nil
      end

      if attributes.key?(:'ad_external_id')
        self.ad_external_id = attributes[:'ad_external_id']
      else
        self.ad_external_id = nil
      end

      if attributes.key?(:'campaign_external_id')
        self.campaign_external_id = attributes[:'campaign_external_id']
      else
        self.campaign_external_id = nil
      end

      if attributes.key?(:'adset_external_id')
        self.adset_external_id = attributes[:'adset_external_id']
      else
        self.adset_external_id = nil
      end

      if attributes.key?(:'date')
        self.date = attributes[:'date']
      else
        self.date = nil
      end

      if attributes.key?(:'account_currency')
        self.account_currency = attributes[:'account_currency']
      else
        self.account_currency = nil
      end

      if attributes.key?(:'spend')
        self.spend = attributes[:'spend']
      else
        self.spend = nil
      end

      if attributes.key?(:'impressions')
        self.impressions = attributes[:'impressions']
      else
        self.impressions = nil
      end

      if attributes.key?(:'clicks')
        self.clicks = attributes[:'clicks']
      else
        self.clicks = nil
      end

      if attributes.key?(:'inline_link_clicks')
        self.inline_link_clicks = attributes[:'inline_link_clicks']
      else
        self.inline_link_clicks = nil
      end

      if attributes.key?(:'actions')
        self.actions = attributes[:'actions']
      else
        self.actions = nil
      end

      if attributes.key?(:'action_values')
        self.action_values = attributes[:'action_values']
      else
        self.action_values = nil
      end

      if attributes.key?(:'fetched_at')
        self.fetched_at = attributes[:'fetched_at']
      else
        self.fetched_at = nil
      end

      if attributes.key?(:'arrivals')
        self.arrivals = attributes[:'arrivals']
      else
        self.arrivals = nil
      end

      if attributes.key?(:'creative_id')
        self.creative_id = attributes[:'creative_id']
      else
        self.creative_id = nil
      end

      if attributes.key?(:'generator')
        self.generator = attributes[:'generator']
      else
        self.generator = nil
      end

      if attributes.key?(:'generator_job')
        self.generator_job = attributes[:'generator_job']
      else
        self.generator_job = nil
      end

      if attributes.key?(:'parent_creative')
        self.parent_creative = attributes[:'parent_creative']
      else
        self.parent_creative = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @platform_ad_account_id.nil?
        invalid_properties.push('invalid value for "platform_ad_account_id", platform_ad_account_id cannot be nil.')
      end

      if @ad_external_id.nil?
        invalid_properties.push('invalid value for "ad_external_id", ad_external_id cannot be nil.')
      end

      if @date.nil?
        invalid_properties.push('invalid value for "date", date cannot be nil.')
      end

      if @account_currency.nil?
        invalid_properties.push('invalid value for "account_currency", account_currency cannot be nil.')
      end

      if @spend.nil?
        invalid_properties.push('invalid value for "spend", spend cannot be nil.')
      end

      if @impressions.nil?
        invalid_properties.push('invalid value for "impressions", impressions cannot be nil.')
      end

      if @clicks.nil?
        invalid_properties.push('invalid value for "clicks", clicks cannot be nil.')
      end

      if @inline_link_clicks.nil?
        invalid_properties.push('invalid value for "inline_link_clicks", inline_link_clicks cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @platform_ad_account_id.nil?
      return false if @ad_external_id.nil?
      return false if @date.nil?
      return false if @account_currency.nil?
      return false if @spend.nil?
      return false if @impressions.nil?
      return false if @clicks.nil?
      return false if @inline_link_clicks.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_ad_account_id Value to be assigned
    def platform_ad_account_id=(platform_ad_account_id)
      if platform_ad_account_id.nil?
        fail ArgumentError, 'platform_ad_account_id cannot be nil'
      end

      @platform_ad_account_id = platform_ad_account_id
    end

    # Custom attribute writer method with validation
    # @param [Object] ad_external_id Value to be assigned
    def ad_external_id=(ad_external_id)
      if ad_external_id.nil?
        fail ArgumentError, 'ad_external_id cannot be nil'
      end

      @ad_external_id = ad_external_id
    end

    # Custom attribute writer method with validation
    # @param [Object] date Value to be assigned
    def date=(date)
      if date.nil?
        fail ArgumentError, 'date cannot be nil'
      end

      @date = date
    end

    # Custom attribute writer method with validation
    # @param [Object] account_currency Value to be assigned
    def account_currency=(account_currency)
      if account_currency.nil?
        fail ArgumentError, 'account_currency cannot be nil'
      end

      @account_currency = account_currency
    end

    # Custom attribute writer method with validation
    # @param [Object] spend Value to be assigned
    def spend=(spend)
      if spend.nil?
        fail ArgumentError, 'spend cannot be nil'
      end

      @spend = spend
    end

    # Custom attribute writer method with validation
    # @param [Object] impressions Value to be assigned
    def impressions=(impressions)
      if impressions.nil?
        fail ArgumentError, 'impressions cannot be nil'
      end

      @impressions = impressions
    end

    # Custom attribute writer method with validation
    # @param [Object] clicks Value to be assigned
    def clicks=(clicks)
      if clicks.nil?
        fail ArgumentError, 'clicks cannot be nil'
      end

      @clicks = clicks
    end

    # Custom attribute writer method with validation
    # @param [Object] inline_link_clicks Value to be assigned
    def inline_link_clicks=(inline_link_clicks)
      if inline_link_clicks.nil?
        fail ArgumentError, 'inline_link_clicks cannot be nil'
      end

      @inline_link_clicks = inline_link_clicks
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          platform_ad_account_id == o.platform_ad_account_id &&
          ad_external_id == o.ad_external_id &&
          campaign_external_id == o.campaign_external_id &&
          adset_external_id == o.adset_external_id &&
          date == o.date &&
          account_currency == o.account_currency &&
          spend == o.spend &&
          impressions == o.impressions &&
          clicks == o.clicks &&
          inline_link_clicks == o.inline_link_clicks &&
          actions == o.actions &&
          action_values == o.action_values &&
          fetched_at == o.fetched_at &&
          arrivals == o.arrivals &&
          creative_id == o.creative_id &&
          generator == o.generator &&
          generator_job == o.generator_job &&
          parent_creative == o.parent_creative
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, platform_ad_account_id, ad_external_id, campaign_external_id, adset_external_id, date, account_currency, spend, impressions, clicks, inline_link_clicks, actions, action_values, fetched_at, arrivals, creative_id, generator, generator_job, parent_creative].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
