=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ListEvents200ResponseEvents < ApiModelBase
    attr_accessor :current_page

    attr_accessor :data

    attr_accessor :first_page_url

    attr_accessor :from

    attr_accessor :last_page

    attr_accessor :last_page_url

    attr_accessor :links

    attr_accessor :next_page_url

    attr_accessor :path

    attr_accessor :per_page

    attr_accessor :prev_page_url

    attr_accessor :to

    attr_accessor :total

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'current_page' => :'current_page',
        :'data' => :'data',
        :'first_page_url' => :'first_page_url',
        :'from' => :'from',
        :'last_page' => :'last_page',
        :'last_page_url' => :'last_page_url',
        :'links' => :'links',
        :'next_page_url' => :'next_page_url',
        :'path' => :'path',
        :'per_page' => :'per_page',
        :'prev_page_url' => :'prev_page_url',
        :'to' => :'to',
        :'total' => :'total'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'current_page' => :'Integer',
        :'data' => :'Array<GetEvent200ResponseEvent>',
        :'first_page_url' => :'String',
        :'from' => :'Integer',
        :'last_page' => :'Integer',
        :'last_page_url' => :'String',
        :'links' => :'Array<ListEvents200ResponseEventsLinksInner>',
        :'next_page_url' => :'String',
        :'path' => :'String',
        :'per_page' => :'Integer',
        :'prev_page_url' => :'String',
        :'to' => :'Integer',
        :'total' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'first_page_url',
        :'from',
        :'last_page_url',
        :'next_page_url',
        :'path',
        :'prev_page_url',
        :'to',
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ListEvents200ResponseEvents` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ListEvents200ResponseEvents`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'current_page')
        self.current_page = attributes[:'current_page']
      else
        self.current_page = nil
      end

      if attributes.key?(:'data')
        if (value = attributes[:'data']).is_a?(Array)
          self.data = value
        end
      else
        self.data = nil
      end

      if attributes.key?(:'first_page_url')
        self.first_page_url = attributes[:'first_page_url']
      else
        self.first_page_url = nil
      end

      if attributes.key?(:'from')
        self.from = attributes[:'from']
      else
        self.from = nil
      end

      if attributes.key?(:'last_page')
        self.last_page = attributes[:'last_page']
      else
        self.last_page = nil
      end

      if attributes.key?(:'last_page_url')
        self.last_page_url = attributes[:'last_page_url']
      else
        self.last_page_url = nil
      end

      if attributes.key?(:'links')
        if (value = attributes[:'links']).is_a?(Array)
          self.links = value
        end
      else
        self.links = nil
      end

      if attributes.key?(:'next_page_url')
        self.next_page_url = attributes[:'next_page_url']
      else
        self.next_page_url = nil
      end

      if attributes.key?(:'path')
        self.path = attributes[:'path']
      else
        self.path = nil
      end

      if attributes.key?(:'per_page')
        self.per_page = attributes[:'per_page']
      else
        self.per_page = nil
      end

      if attributes.key?(:'prev_page_url')
        self.prev_page_url = attributes[:'prev_page_url']
      else
        self.prev_page_url = nil
      end

      if attributes.key?(:'to')
        self.to = attributes[:'to']
      else
        self.to = nil
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      else
        self.total = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @current_page.nil?
        invalid_properties.push('invalid value for "current_page", current_page cannot be nil.')
      end

      if @data.nil?
        invalid_properties.push('invalid value for "data", data cannot be nil.')
      end

      if @last_page.nil?
        invalid_properties.push('invalid value for "last_page", last_page cannot be nil.')
      end

      if @links.nil?
        invalid_properties.push('invalid value for "links", links cannot be nil.')
      end

      if @per_page.nil?
        invalid_properties.push('invalid value for "per_page", per_page cannot be nil.')
      end

      if @total.nil?
        invalid_properties.push('invalid value for "total", total cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @current_page.nil?
      return false if @data.nil?
      return false if @last_page.nil?
      return false if @links.nil?
      return false if @per_page.nil?
      return false if @total.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] current_page Value to be assigned
    def current_page=(current_page)
      if current_page.nil?
        fail ArgumentError, 'current_page cannot be nil'
      end

      @current_page = current_page
    end

    # Custom attribute writer method with validation
    # @param [Object] data Value to be assigned
    def data=(data)
      if data.nil?
        fail ArgumentError, 'data cannot be nil'
      end

      @data = data
    end

    # Custom attribute writer method with validation
    # @param [Object] last_page Value to be assigned
    def last_page=(last_page)
      if last_page.nil?
        fail ArgumentError, 'last_page cannot be nil'
      end

      @last_page = last_page
    end

    # Custom attribute writer method with validation
    # @param [Object] links Value to be assigned
    def links=(links)
      if links.nil?
        fail ArgumentError, 'links cannot be nil'
      end

      @links = links
    end

    # Custom attribute writer method with validation
    # @param [Object] per_page Value to be assigned
    def per_page=(per_page)
      if per_page.nil?
        fail ArgumentError, 'per_page cannot be nil'
      end

      @per_page = per_page
    end

    # Custom attribute writer method with validation
    # @param [Object] total Value to be assigned
    def total=(total)
      if total.nil?
        fail ArgumentError, 'total cannot be nil'
      end

      @total = total
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          current_page == o.current_page &&
          data == o.data &&
          first_page_url == o.first_page_url &&
          from == o.from &&
          last_page == o.last_page &&
          last_page_url == o.last_page_url &&
          links == o.links &&
          next_page_url == o.next_page_url &&
          path == o.path &&
          per_page == o.per_page &&
          prev_page_url == o.prev_page_url &&
          to == o.to &&
          total == o.total
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [current_page, data, first_page_url, from, last_page, last_page_url, links, next_page_url, path, per_page, prev_page_url, to, total].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
