=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class PlanCopyReadPlan < ApiModelBase
    attr_accessor :id

    attr_accessor :platform_ad_account_id

    attr_accessor :status

    attr_accessor :budget_amount_minor

    attr_accessor :validation_result

    attr_accessor :validated_at

    attr_accessor :approval_id

    class EnumAttributeValidator
      attr_reader :datatype
      attr_reader :allowable_values

      def initialize(datatype, allowable_values)
        @allowable_values = allowable_values.map do |value|
          case datatype.to_s
          when /Integer/i
            value.to_i
          when /Float/i
            value.to_f
          else
            value
          end
        end
      end

      def valid?(value)
        !value || allowable_values.include?(value)
      end
    end

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'platform_ad_account_id' => :'platform_ad_account_id',
        :'status' => :'status',
        :'budget_amount_minor' => :'budget_amount_minor',
        :'validation_result' => :'validation_result',
        :'validated_at' => :'validated_at',
        :'approval_id' => :'approval_id'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'String',
        :'platform_ad_account_id' => :'Integer',
        :'status' => :'String',
        :'budget_amount_minor' => :'Integer',
        :'validation_result' => :'Object',
        :'validated_at' => :'Object',
        :'approval_id' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'validation_result',
        :'validated_at',
        :'approval_id'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::PlanCopyReadPlan` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::PlanCopyReadPlan`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'platform_ad_account_id')
        self.platform_ad_account_id = attributes[:'platform_ad_account_id']
      else
        self.platform_ad_account_id = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'budget_amount_minor')
        self.budget_amount_minor = attributes[:'budget_amount_minor']
      else
        self.budget_amount_minor = nil
      end

      if attributes.key?(:'validation_result')
        if (value = attributes[:'validation_result']).is_a?(Hash)
          self.validation_result = value
        end
        self.validation_result = attributes[:'validation_result']
      else
        self.validation_result = nil
      end

      if attributes.key?(:'validated_at')
        if (value = attributes[:'validated_at']).is_a?(Hash)
          self.validated_at = value
        end
        self.validated_at = attributes[:'validated_at']
      else
        self.validated_at = nil
      end

      if attributes.key?(:'approval_id')
        if (value = attributes[:'approval_id']).is_a?(Hash)
          self.approval_id = value
        end
        self.approval_id = attributes[:'approval_id']
      else
        self.approval_id = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @platform_ad_account_id.nil?
        invalid_properties.push('invalid value for "platform_ad_account_id", platform_ad_account_id cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      if @budget_amount_minor.nil?
        invalid_properties.push('invalid value for "budget_amount_minor", budget_amount_minor cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @platform_ad_account_id.nil?
      return false if @status.nil?
      status_validator = EnumAttributeValidator.new('String', ["draft"])
      return false unless status_validator.valid?(@status)
      return false if @budget_amount_minor.nil?
      validation_result_validator = EnumAttributeValidator.new('Object', [])
      return false unless validation_result_validator.valid?(@validation_result)
      validated_at_validator = EnumAttributeValidator.new('Object', [])
      return false unless validated_at_validator.valid?(@validated_at)
      approval_id_validator = EnumAttributeValidator.new('Object', [])
      return false unless approval_id_validator.valid?(@approval_id)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] platform_ad_account_id Value to be assigned
    def platform_ad_account_id=(platform_ad_account_id)
      if platform_ad_account_id.nil?
        fail ArgumentError, 'platform_ad_account_id cannot be nil'
      end

      @platform_ad_account_id = platform_ad_account_id
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] status Object to be assigned
    def status=(status)
      validator = EnumAttributeValidator.new('String', ["draft"])
      unless validator.valid?(status)
        fail ArgumentError, "invalid value for \"status\", must be one of #{validator.allowable_values}."
      end
      @status = status
    end

    # Custom attribute writer method with validation
    # @param [Object] budget_amount_minor Value to be assigned
    def budget_amount_minor=(budget_amount_minor)
      if budget_amount_minor.nil?
        fail ArgumentError, 'budget_amount_minor cannot be nil'
      end

      @budget_amount_minor = budget_amount_minor
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] validation_result Object to be assigned
    def validation_result=(validation_result)
      validator = EnumAttributeValidator.new('Object', [])
      unless validator.valid?(validation_result)
        fail ArgumentError, "invalid value for \"validation_result\", must be one of #{validator.allowable_values}."
      end
      @validation_result = validation_result
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] validated_at Object to be assigned
    def validated_at=(validated_at)
      validator = EnumAttributeValidator.new('Object', [])
      unless validator.valid?(validated_at)
        fail ArgumentError, "invalid value for \"validated_at\", must be one of #{validator.allowable_values}."
      end
      @validated_at = validated_at
    end

    # Custom attribute writer method checking allowed values (enum).
    # @param [Object] approval_id Object to be assigned
    def approval_id=(approval_id)
      validator = EnumAttributeValidator.new('Object', [])
      unless validator.valid?(approval_id)
        fail ArgumentError, "invalid value for \"approval_id\", must be one of #{validator.allowable_values}."
      end
      @approval_id = approval_id
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          platform_ad_account_id == o.platform_ad_account_id &&
          status == o.status &&
          budget_amount_minor == o.budget_amount_minor &&
          validation_result == o.validation_result &&
          validated_at == o.validated_at &&
          approval_id == o.approval_id
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, platform_ad_account_id, status, budget_amount_minor, validation_result, validated_at, approval_id].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
