=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ReconciliationReport < ApiModelBase
    attr_accessor :id

    attr_accessor :signal_tracker_id

    attr_accessor :destination_id

    attr_accessor :report_date

    attr_accessor :accepted_count

    attr_accessor :meta_count

    attr_accessor :observed_gap

    attr_accessor :event_counts

    attr_accessor :buckets

    attr_accessor :unexplained_residual

    attr_accessor :status

    attr_accessor :created_at

    attr_accessor :updated_at

    attr_accessor :claimed_clicks

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'id' => :'id',
        :'signal_tracker_id' => :'signal_tracker_id',
        :'destination_id' => :'destination_id',
        :'report_date' => :'report_date',
        :'accepted_count' => :'accepted_count',
        :'meta_count' => :'meta_count',
        :'observed_gap' => :'observed_gap',
        :'event_counts' => :'event_counts',
        :'buckets' => :'buckets',
        :'unexplained_residual' => :'unexplained_residual',
        :'status' => :'status',
        :'created_at' => :'created_at',
        :'updated_at' => :'updated_at',
        :'claimed_clicks' => :'claimed_clicks'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'id' => :'Integer',
        :'signal_tracker_id' => :'String',
        :'destination_id' => :'String',
        :'report_date' => :'Time',
        :'accepted_count' => :'Integer',
        :'meta_count' => :'Integer',
        :'observed_gap' => :'Integer',
        :'event_counts' => :'Array<Object>',
        :'buckets' => :'Array<Object>',
        :'unexplained_residual' => :'Integer',
        :'status' => :'String',
        :'created_at' => :'Time',
        :'updated_at' => :'Time',
        :'claimed_clicks' => :'Integer'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
        :'created_at',
        :'updated_at',
        :'claimed_clicks'
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ReconciliationReport` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ReconciliationReport`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'id')
        self.id = attributes[:'id']
      else
        self.id = nil
      end

      if attributes.key?(:'signal_tracker_id')
        self.signal_tracker_id = attributes[:'signal_tracker_id']
      else
        self.signal_tracker_id = nil
      end

      if attributes.key?(:'destination_id')
        self.destination_id = attributes[:'destination_id']
      else
        self.destination_id = nil
      end

      if attributes.key?(:'report_date')
        self.report_date = attributes[:'report_date']
      else
        self.report_date = nil
      end

      if attributes.key?(:'accepted_count')
        self.accepted_count = attributes[:'accepted_count']
      else
        self.accepted_count = nil
      end

      if attributes.key?(:'meta_count')
        self.meta_count = attributes[:'meta_count']
      else
        self.meta_count = nil
      end

      if attributes.key?(:'observed_gap')
        self.observed_gap = attributes[:'observed_gap']
      else
        self.observed_gap = nil
      end

      if attributes.key?(:'event_counts')
        if (value = attributes[:'event_counts']).is_a?(Array)
          self.event_counts = value
        end
      else
        self.event_counts = nil
      end

      if attributes.key?(:'buckets')
        if (value = attributes[:'buckets']).is_a?(Array)
          self.buckets = value
        end
      else
        self.buckets = nil
      end

      if attributes.key?(:'unexplained_residual')
        self.unexplained_residual = attributes[:'unexplained_residual']
      else
        self.unexplained_residual = nil
      end

      if attributes.key?(:'status')
        self.status = attributes[:'status']
      else
        self.status = nil
      end

      if attributes.key?(:'created_at')
        self.created_at = attributes[:'created_at']
      else
        self.created_at = nil
      end

      if attributes.key?(:'updated_at')
        self.updated_at = attributes[:'updated_at']
      else
        self.updated_at = nil
      end

      if attributes.key?(:'claimed_clicks')
        self.claimed_clicks = attributes[:'claimed_clicks']
      else
        self.claimed_clicks = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @id.nil?
        invalid_properties.push('invalid value for "id", id cannot be nil.')
      end

      if @signal_tracker_id.nil?
        invalid_properties.push('invalid value for "signal_tracker_id", signal_tracker_id cannot be nil.')
      end

      if @destination_id.nil?
        invalid_properties.push('invalid value for "destination_id", destination_id cannot be nil.')
      end

      if @report_date.nil?
        invalid_properties.push('invalid value for "report_date", report_date cannot be nil.')
      end

      if @accepted_count.nil?
        invalid_properties.push('invalid value for "accepted_count", accepted_count cannot be nil.')
      end

      if @meta_count.nil?
        invalid_properties.push('invalid value for "meta_count", meta_count cannot be nil.')
      end

      if @observed_gap.nil?
        invalid_properties.push('invalid value for "observed_gap", observed_gap cannot be nil.')
      end

      if @event_counts.nil?
        invalid_properties.push('invalid value for "event_counts", event_counts cannot be nil.')
      end

      if @buckets.nil?
        invalid_properties.push('invalid value for "buckets", buckets cannot be nil.')
      end

      if @unexplained_residual.nil?
        invalid_properties.push('invalid value for "unexplained_residual", unexplained_residual cannot be nil.')
      end

      if @status.nil?
        invalid_properties.push('invalid value for "status", status cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @id.nil?
      return false if @signal_tracker_id.nil?
      return false if @destination_id.nil?
      return false if @report_date.nil?
      return false if @accepted_count.nil?
      return false if @meta_count.nil?
      return false if @observed_gap.nil?
      return false if @event_counts.nil?
      return false if @buckets.nil?
      return false if @unexplained_residual.nil?
      return false if @status.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] id Value to be assigned
    def id=(id)
      if id.nil?
        fail ArgumentError, 'id cannot be nil'
      end

      @id = id
    end

    # Custom attribute writer method with validation
    # @param [Object] signal_tracker_id Value to be assigned
    def signal_tracker_id=(signal_tracker_id)
      if signal_tracker_id.nil?
        fail ArgumentError, 'signal_tracker_id cannot be nil'
      end

      @signal_tracker_id = signal_tracker_id
    end

    # Custom attribute writer method with validation
    # @param [Object] destination_id Value to be assigned
    def destination_id=(destination_id)
      if destination_id.nil?
        fail ArgumentError, 'destination_id cannot be nil'
      end

      @destination_id = destination_id
    end

    # Custom attribute writer method with validation
    # @param [Object] report_date Value to be assigned
    def report_date=(report_date)
      if report_date.nil?
        fail ArgumentError, 'report_date cannot be nil'
      end

      @report_date = report_date
    end

    # Custom attribute writer method with validation
    # @param [Object] accepted_count Value to be assigned
    def accepted_count=(accepted_count)
      if accepted_count.nil?
        fail ArgumentError, 'accepted_count cannot be nil'
      end

      @accepted_count = accepted_count
    end

    # Custom attribute writer method with validation
    # @param [Object] meta_count Value to be assigned
    def meta_count=(meta_count)
      if meta_count.nil?
        fail ArgumentError, 'meta_count cannot be nil'
      end

      @meta_count = meta_count
    end

    # Custom attribute writer method with validation
    # @param [Object] observed_gap Value to be assigned
    def observed_gap=(observed_gap)
      if observed_gap.nil?
        fail ArgumentError, 'observed_gap cannot be nil'
      end

      @observed_gap = observed_gap
    end

    # Custom attribute writer method with validation
    # @param [Object] event_counts Value to be assigned
    def event_counts=(event_counts)
      if event_counts.nil?
        fail ArgumentError, 'event_counts cannot be nil'
      end

      @event_counts = event_counts
    end

    # Custom attribute writer method with validation
    # @param [Object] buckets Value to be assigned
    def buckets=(buckets)
      if buckets.nil?
        fail ArgumentError, 'buckets cannot be nil'
      end

      @buckets = buckets
    end

    # Custom attribute writer method with validation
    # @param [Object] unexplained_residual Value to be assigned
    def unexplained_residual=(unexplained_residual)
      if unexplained_residual.nil?
        fail ArgumentError, 'unexplained_residual cannot be nil'
      end

      @unexplained_residual = unexplained_residual
    end

    # Custom attribute writer method with validation
    # @param [Object] status Value to be assigned
    def status=(status)
      if status.nil?
        fail ArgumentError, 'status cannot be nil'
      end

      @status = status
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          id == o.id &&
          signal_tracker_id == o.signal_tracker_id &&
          destination_id == o.destination_id &&
          report_date == o.report_date &&
          accepted_count == o.accepted_count &&
          meta_count == o.meta_count &&
          observed_gap == o.observed_gap &&
          event_counts == o.event_counts &&
          buckets == o.buckets &&
          unexplained_residual == o.unexplained_residual &&
          status == o.status &&
          created_at == o.created_at &&
          updated_at == o.updated_at &&
          claimed_clicks == o.claimed_clicks
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [id, signal_tracker_id, destination_id, report_date, accepted_count, meta_count, observed_gap, event_counts, buckets, unexplained_residual, status, created_at, updated_at, claimed_clicks].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
