=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  class ReplayDeliveries202Response < ApiModelBase
    attr_accessor :queued

    attr_accessor :expired

    attr_accessor :payload_expired

    attr_accessor :capped

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'queued' => :'queued',
        :'expired' => :'expired',
        :'payload_expired' => :'payload_expired',
        :'capped' => :'capped'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'queued' => :'Integer',
        :'expired' => :'Integer',
        :'payload_expired' => :'Integer',
        :'capped' => :'Boolean'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::ReplayDeliveries202Response` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::ReplayDeliveries202Response`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'queued')
        self.queued = attributes[:'queued']
      else
        self.queued = nil
      end

      if attributes.key?(:'expired')
        self.expired = attributes[:'expired']
      else
        self.expired = nil
      end

      if attributes.key?(:'payload_expired')
        self.payload_expired = attributes[:'payload_expired']
      else
        self.payload_expired = nil
      end

      if attributes.key?(:'capped')
        self.capped = attributes[:'capped']
      else
        self.capped = nil
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if @queued.nil?
        invalid_properties.push('invalid value for "queued", queued cannot be nil.')
      end

      if @expired.nil?
        invalid_properties.push('invalid value for "expired", expired cannot be nil.')
      end

      if @payload_expired.nil?
        invalid_properties.push('invalid value for "payload_expired", payload_expired cannot be nil.')
      end

      if @capped.nil?
        invalid_properties.push('invalid value for "capped", capped cannot be nil.')
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if @queued.nil?
      return false if @expired.nil?
      return false if @payload_expired.nil?
      return false if @capped.nil?
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] queued Value to be assigned
    def queued=(queued)
      if queued.nil?
        fail ArgumentError, 'queued cannot be nil'
      end

      @queued = queued
    end

    # Custom attribute writer method with validation
    # @param [Object] expired Value to be assigned
    def expired=(expired)
      if expired.nil?
        fail ArgumentError, 'expired cannot be nil'
      end

      @expired = expired
    end

    # Custom attribute writer method with validation
    # @param [Object] payload_expired Value to be assigned
    def payload_expired=(payload_expired)
      if payload_expired.nil?
        fail ArgumentError, 'payload_expired cannot be nil'
      end

      @payload_expired = payload_expired
    end

    # Custom attribute writer method with validation
    # @param [Object] capped Value to be assigned
    def capped=(capped)
      if capped.nil?
        fail ArgumentError, 'capped cannot be nil'
      end

      @capped = capped
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          queued == o.queued &&
          expired == o.expired &&
          payload_expired == o.payload_expired &&
          capped == o.capped
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [queued, expired, payload_expired, capped].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
