=begin
#Plainrouter Conversion API

#Plainrouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

require 'date'
require 'time'

module PlainRouter::OpenAPI
  # Optional flat map of at most 32 string tags; reserved keys count toward the cap. For a creative from an outside tool, set generator and generator_job, plus parent_creative for a variation. Values are stored unchanged. PlainRouter’s own creative tools will set these on every creative they make; intake performs no generation, rendering or scoring.
  class StoreCreativeFromUrlRequestTags < ApiModelBase
    # Lowercase slug naming the outside tool that made the creative.
    attr_accessor :generator

    # Printable characters naming the tool’s job or render; control and other non-printable characters are refused.
    attr_accessor :generator_job

    # The id returned by the creative APIs: a lowercase ULID of an existing creative in the same workspace that this creative varies.
    attr_accessor :parent_creative

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'generator' => :'generator',
        :'generator_job' => :'generator_job',
        :'parent_creative' => :'parent_creative'
      }
    end

    # Returns attribute mapping this model knows about
    def self.acceptable_attribute_map
      attribute_map
    end

    # Returns all the JSON keys this model knows about
    def self.acceptable_attributes
      acceptable_attribute_map.values
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'generator' => :'String',
        :'generator_job' => :'String',
        :'parent_creative' => :'String'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `PlainRouter::OpenAPI::StoreCreativeFromUrlRequestTags` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      acceptable_attribute_map = self.class.acceptable_attribute_map
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!acceptable_attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `PlainRouter::OpenAPI::StoreCreativeFromUrlRequestTags`. Please check the name to make sure it's valid. List of attributes: " + acceptable_attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'generator')
        self.generator = attributes[:'generator']
      end

      if attributes.key?(:'generator_job')
        self.generator_job = attributes[:'generator_job']
      end

      if attributes.key?(:'parent_creative')
        self.parent_creative = attributes[:'parent_creative']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      warn '[DEPRECATED] the `list_invalid_properties` method is obsolete'
      invalid_properties = Array.new
      if !@generator.nil? && @generator.to_s.length > 64
        invalid_properties.push('invalid value for "generator", the character length must be smaller than or equal to 64.')
      end

      if !@generator.nil? && @generator.to_s.length < 1
        invalid_properties.push('invalid value for "generator", the character length must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^[a-z0-9-]{1,64}$/)
      if !@generator.nil? && @generator !~ pattern
        invalid_properties.push("invalid value for \"generator\", must conform to the pattern #{pattern}.")
      end

      if !@generator_job.nil? && @generator_job.to_s.length > 255
        invalid_properties.push('invalid value for "generator_job", the character length must be smaller than or equal to 255.')
      end

      if !@generator_job.nil? && @generator_job.to_s.length < 1
        invalid_properties.push('invalid value for "generator_job", the character length must be greater than or equal to 1.')
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if !@parent_creative.nil? && @parent_creative !~ pattern
        invalid_properties.push("invalid value for \"parent_creative\", must conform to the pattern #{pattern}.")
      end

      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      warn '[DEPRECATED] the `valid?` method is obsolete'
      return false if !@generator.nil? && @generator.to_s.length > 64
      return false if !@generator.nil? && @generator.to_s.length < 1
      return false if !@generator.nil? && @generator !~ Regexp.new(/^[a-z0-9-]{1,64}$/)
      return false if !@generator_job.nil? && @generator_job.to_s.length > 255
      return false if !@generator_job.nil? && @generator_job.to_s.length < 1
      return false if !@parent_creative.nil? && @parent_creative !~ Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      true
    end

    # Custom attribute writer method with validation
    # @param [Object] generator Value to be assigned
    def generator=(generator)
      if generator.nil?
        fail ArgumentError, 'generator cannot be nil'
      end

      if generator.to_s.length > 64
        fail ArgumentError, 'invalid value for "generator", the character length must be smaller than or equal to 64.'
      end

      if generator.to_s.length < 1
        fail ArgumentError, 'invalid value for "generator", the character length must be greater than or equal to 1.'
      end

      pattern = Regexp.new(/^[a-z0-9-]{1,64}$/)
      if generator !~ pattern
        fail ArgumentError, "invalid value for \"generator\", must conform to the pattern #{pattern}."
      end

      @generator = generator
    end

    # Custom attribute writer method with validation
    # @param [Object] generator_job Value to be assigned
    def generator_job=(generator_job)
      if generator_job.nil?
        fail ArgumentError, 'generator_job cannot be nil'
      end

      if generator_job.to_s.length > 255
        fail ArgumentError, 'invalid value for "generator_job", the character length must be smaller than or equal to 255.'
      end

      if generator_job.to_s.length < 1
        fail ArgumentError, 'invalid value for "generator_job", the character length must be greater than or equal to 1.'
      end

      @generator_job = generator_job
    end

    # Custom attribute writer method with validation
    # @param [Object] parent_creative Value to be assigned
    def parent_creative=(parent_creative)
      if parent_creative.nil?
        fail ArgumentError, 'parent_creative cannot be nil'
      end

      pattern = Regexp.new(/^[0-7][0-9a-hjkmnp-tv-z]{25}$/)
      if parent_creative !~ pattern
        fail ArgumentError, "invalid value for \"parent_creative\", must conform to the pattern #{pattern}."
      end

      @parent_creative = parent_creative
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          generator == o.generator &&
          generator_job == o.generator_job &&
          parent_creative == o.parent_creative
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [generator, generator_job, parent_creative].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      attributes = attributes.transform_keys(&:to_sym)
      transformed_hash = {}
      openapi_types.each_pair do |key, type|
        if attributes.key?(attribute_map[key]) && attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = nil
        elsif type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[attribute_map[key]].is_a?(Array)
            transformed_hash["#{key}"] = attributes[attribute_map[key]].map { |v| _deserialize($1, v) }
          end
        elsif !attributes[attribute_map[key]].nil?
          transformed_hash["#{key}"] = _deserialize(type, attributes[attribute_map[key]])
        end
      end
      new(transformed_hash)
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

  end

end
