=begin
#PlainRouter Conversion API

#PlainRouter public Signals Conversion API.

The version of the OpenAPI document: 0.5.0

Generated by: https://openapi-generator.tech
Generator version: 7.25.0

=end

# Common files
require 'plainrouter/openapi/api_client'
require 'plainrouter/openapi/api_error'
require 'plainrouter/openapi/api_model_base'
require 'plainrouter/openapi/version'
require 'plainrouter/openapi/configuration'

# Models
require 'plainrouter/openapi/models/create_event200_response'
require 'plainrouter/openapi/models/create_event_request'
require 'plainrouter/openapi/models/create_event_request_any_of'
require 'plainrouter/openapi/models/create_event_request_any_of1'
require 'plainrouter/openapi/models/create_event_request_any_of_event_time'
require 'plainrouter/openapi/models/create_event_request_any_of_value_data'
require 'plainrouter/openapi/models/create_sandbox_key201_response'
require 'plainrouter/openapi/models/create_sandbox_key201_response_use'
require 'plainrouter/openapi/models/delete_user_data200_response'
require 'plainrouter/openapi/models/delete_user_data_request'
require 'plainrouter/openapi/models/delivery_status'
require 'plainrouter/openapi/models/destination'
require 'plainrouter/openapi/models/destination_credential_source'
require 'plainrouter/openapi/models/destination_status'
require 'plainrouter/openapi/models/destination_type'
require 'plainrouter/openapi/models/emq_snapshot'
require 'plainrouter/openapi/models/error_message'
require 'plainrouter/openapi/models/event'
require 'plainrouter/openapi/models/get_emq_report200_response'
require 'plainrouter/openapi/models/get_emq_report200_response_snapshots_inner'
require 'plainrouter/openapi/models/get_event200_response'
require 'plainrouter/openapi/models/get_event200_response_deliveries_inner'
require 'plainrouter/openapi/models/get_event200_response_event'
require 'plainrouter/openapi/models/get_event200_response_event_consent'
require 'plainrouter/openapi/models/get_event200_response_event_deliveries_inner'
require 'plainrouter/openapi/models/get_event200_response_lineage'
require 'plainrouter/openapi/models/get_event200_response_lineage_children_inner'
require 'plainrouter/openapi/models/get_event200_response_lineage_parent'
require 'plainrouter/openapi/models/get_reconciliation_report200_response'
require 'plainrouter/openapi/models/get_reconciliation_report200_response_reports_inner'
require 'plainrouter/openapi/models/get_reconciliation_report200_response_reports_inner_buckets_value'
require 'plainrouter/openapi/models/get_reconciliation_report200_response_reports_inner_event_counts'
require 'plainrouter/openapi/models/get_reconciliation_report200_response_reports_inner_event_counts_accepted'
require 'plainrouter/openapi/models/get_sandbox200_response'
require 'plainrouter/openapi/models/get_sandbox200_response_self_serve_key'
require 'plainrouter/openapi/models/get_sandbox200_response_try'
require 'plainrouter/openapi/models/get_sandbox200_response_try_body'
require 'plainrouter/openapi/models/get_sandbox200_response_try_body_value_data'
require 'plainrouter/openapi/models/jurisdiction_policy_class'
require 'plainrouter/openapi/models/list_events200_response'
require 'plainrouter/openapi/models/list_events200_response_events'
require 'plainrouter/openapi/models/list_events200_response_events_links_inner'
require 'plainrouter/openapi/models/list_events200_response_metrics'
require 'plainrouter/openapi/models/list_events_by_cursor200_response'
require 'plainrouter/openapi/models/list_events_by_cursor200_response_events'
require 'plainrouter/openapi/models/reconciliation_report'
require 'plainrouter/openapi/models/replay_deliveries202_response'
require 'plainrouter/openapi/models/replay_deliveries_request'
require 'plainrouter/openapi/models/send_test_purchase200_response'
require 'plainrouter/openapi/models/send_test_purchase422_response'
require 'plainrouter/openapi/models/send_test_purchase_request'
require 'plainrouter/openapi/models/set_destination_test_mode200_response'
require 'plainrouter/openapi/models/set_destination_test_mode200_response_destination'
require 'plainrouter/openapi/models/set_destination_test_mode_request'
require 'plainrouter/openapi/models/traffic_class'
require 'plainrouter/openapi/models/validate_sandbox_event200_response'
require 'plainrouter/openapi/models/validate_sandbox_event_request'
require 'plainrouter/openapi/models/validate_sandbox_event_request_value_data'
require 'plainrouter/openapi/models/validation_error'

# APIs
require 'plainrouter/openapi/api/event_api'
require 'plainrouter/openapi/api/operations_api'
require 'plainrouter/openapi/api/sandbox_api'

module PlainRouter::OpenAPI
  class << self
    # Customize default settings for the SDK using block.
    #   PlainRouter::OpenAPI.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
